### ISSUE TITLE
/data/user/0/juniojsv.mtk.easy.su/files/magisk-boot.sh[13]: dirname: can't execute: Permission denied /data/user/0/juniojsv.mtk.easy.su/files/magisk-boot.sh[113]: cd: /32: No such file or directory exit: 1

### ISSUE THREAD

**Issue by jsphhbna** [JunioJsv/mtk-easy-su#105]
![Screenshot_20210124-214832](https://user-images.githubusercontent.com/77925967/105632654-41ab1f00-5e8f-11eb-8f8b-b29d364925ad.png)
Why does this happening?

**Comment by jsphhbna** [comment]
Help me please

**Comment by Captkaos351** [comment]
/data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[13]: dirname: not found
/data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[113]: cd: /32: No such file or directory
exit: 1
