### ISSUE TITLE
Latest MTK Easy Su not working on device

### ISSUE THREAD

**Issue by TheBeast941** [JunioJsv/mtk-easy-su#119]
Device name: Nokia 2.2
Device model: TA-1188
OS: Android 9, Security patch level 5 October 2019

Installed MTK Easy Su 2.0.4 and root failed, then installed MTK Easy Su 2.0.3 and device was rooted successfully

**Comment by JunioJsv** [comment]
Pls send me a copy of log

**Comment by TheBeast941** [comment]
/data/user/0/juniojsv.mtk.easy.su/files/magisk-boot.sh[124]: ./mtk-su: can't execute: Permission denied
exit: 126

**Comment by JunioJsv** [comment]
try with v2.0.6

**Comment by TheBeast941** [comment]
Works again
