### ISSUE TITLE
Not working on 8.1.0 (LG-M320TV - MT6750)

### ISSUE THREAD

**Issue by Snyver** [JunioJsv/mtk-easy-su#12]
This root method works fine on Android 7.0, but I recently updated my device to Android 8.1.0 (M320N European ROM) and I cannot root my device.

Script return:

param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40f335a0
kallsyms_num_syms 49271, addr_count 49271
kallsyms_names pa 0x40f63790, size 631393
kallsyms_markers pa 0x40ffda00
kallsyms_token_table pa 0x40ffdd10
kallsyms_token_index pa 0x40ffe090
Patching credentials
Parsing current_is_single_threaded
Parsing avc_denied
c045932c: MOVW R0, #0x7604
c0459330: MOVT R0, #0xc190
selinux_enforcing VA: 0xc1907604
Setting selinux_enforcing
Switched selinux to permissivearmv7l machine
Stack protection detected
init_task not found
setns failed: No such file or directory
starting /system/bin/sh
UID: 10398  cap: 0000000000  selinux: permissive  
Root user only
returned 1

**Comment by JunioJsv** [comment]
run sh on terminal emulator and show me stdout

**Comment by JunioJsv** [comment]
Or, ls -l /system/bin/ | grep sh

**Comment by Snyver** [comment]
mlv7:/ $ ls -l /system/bin/ | grep sh
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 acpi -> toybox
-rwxr-xr-x 1 root   shell     1161988 2008-12-31 16:30 adbd
-rwxr-xr-x 1 root   shell       26024 2008-12-31 16:30 aee
-rwxr-xr-x 1 root   shell      297972 2008-12-31 16:30 aee_aed
-rwxr-xr-x 1 root   shell       21928 2008-12-31 16:30 aee_archive
-rwxr-xr-x 1 root   shell      181880 2008-12-31 16:30 aee_dumpstate
-rwxr-xr-x 1 root   shell         207 2008-12-31 16:30 am
lrwxr-xr-x 1 root   shell          13 2008-12-31 16:30 app_process -> app_process32
-rwxr-xr-x 1 root   shell       29104 2008-12-31 16:30 app_process32
-rwxr-xr-x 1 root   shell      226592 2008-12-31 16:30 applypatch
-rwxr-xr-x 1 root   shell          33 2008-12-31 16:30 appops
-rwxr-xr-x 1 root   shell         215 2008-12-31 16:30 appwidget
-rwxr-xr-x 1 root   shell       87056 2008-12-31 16:30 atrace
-rwxr-xr-x 1 root   shell       88492 2008-12-31 16:30 audiocmdservice_atci
-rwxr-xr-x 1 root   shell       20556 2008-12-31 16:30 audioserver
-rwxr-xr-x 1 root   shell       28980 2008-12-31 16:30 badblocks
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 base64 -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 basename -> toybox
-rwxr-xr-x 1 root   shell       47024 2008-12-31 16:30 bcc
-rwxr-xr-x 1 root   shell       20508 2008-12-31 16:30 blkidlrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 blockdev -> toybox
-rwxr-xr-x 1 root   shell         199 2008-12-31 16:30 bmgr
-rwxr-xr-x 1 root   shell       21964 2008-12-31 16:30 bnrd
-rwxr-xr-x 1 root   shell       16280 2008-12-31 16:30 boot_logo_updater
-rwxr-xr-x 1 root   shell       80384 2008-12-31 16:30 bootanimation
-rwxr-xr-x 1 root   shell       41756 2008-12-31 16:30 bootstat
-rwxr-xr-x 1 root   shell         156 2008-12-31 16:30 bu
-rwxr-xr-x 1 root   shell       16196 2008-12-31 16:30 bugreport
-rwxr-xr-x 1 root   shell       16312 2008-12-31 16:30 bugreportz
lrwxr-xr-x 1 root   shell           5 2008-12-31 16:30 bunzip2 -> bzip2
lrwxr-xr-x 1 root   shell           5 2008-12-31 16:30 bzcat -> bzip2
-rwxr-xr-x 1 root   shell      101652 2008-12-31 16:30 bzip2lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cal -> toybox
-rwxr-xr-x 1 root   shell       16240 2008-12-31 16:30 cameraserver
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cat -> toybox
-rwxr-xr-x 1 root   shell       16348 2008-12-31 16:30 ccmd
-rwxr-xr-x 1 root   shell       24452 2008-12-31 16:30 charon
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chcon -> toybox
-rwxr-xr-x 1 root   shell        1124 2008-12-31 16:30 check_data_mount.sh
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chgrp -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chmod -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chown -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chroot -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 chrt -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cksum -> toybox
-rwxr-xr-x 1 root   shell       52872 2008-12-31 16:30 clatdlrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 clear -> toybox
-rwxr-xr-x 1 root   shell       46076 2008-12-31 16:30 cmd
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cmp -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 comm -> toybox
-rwxr-xr-x 1 root   shell         207 2008-12-31 16:30 content
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cp -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cpio -> toybox
-rwxr-xr-x 1 root   shell       97912 2008-12-31 16:30 crash_dump32
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 cut -> toybox
lrwxr-xr-x 1 root   shell          10 2008-12-31 16:30 dalvikvm -> dalvikvm32
-rwxr-xr-x 1 root   shell       24668 2008-12-31 16:30 dalvikvm32
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 date -> toybox
lrwxr-xr-x 1 root   shell           7 2008-12-31 16:30 dd -> toolbox
-rwxr-xr-x 1 root   shell       20448 2008-12-31 16:30 debuggerd
-rwxr-xr-x 1 root   shell      141892 2008-12-31 16:30 dex2oat
-rwxr-xr-x 1 root   shell       32952 2008-12-31 16:30 dexdiag
-rwxr-xr-x 1 root   shell      100292 2008-12-31 16:30 dexdump
-rwxr-xr-x 1 root   shell       20564 2008-12-31 16:30 dexlist
-rwxr-xr-x 1 root   shell       29100 2008-12-31 16:30 dexoptanalyzer
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 df -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 diff -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 dirname -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 dmesg -> toybox
-rwxr-xr-x 1 root   shell      144228 2008-12-31 16:30 dnsmasq
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 dos2unix -> toybox
-rwxr-xr-x 1 root   shell         156 2008-12-31 16:30 dpm
-rwxr-xr-x 1 root   shell       66484 2008-12-31 16:30 drmserver
-rwxr-xr-x 1 root   shell       29540 2008-12-31 16:30 dsqn
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 du -> toybox
-rwxr-xr-x 1 root   shell      218020 2008-12-31 16:30 dumpstate
-rwxr-xr-x 1 root   shell       41872 2008-12-31 16:30 dumpsys
-rwxr-xr-x 1 root   shell      187656 2008-12-31 16:30 e2fsck
-rwxr-xr-x 1 root   shell       29428 2008-12-31 16:30 e2fsdroid
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 echo -> toybox
-rwxr-xr-x 1 root   shell       20688 2008-12-31 16:30 ecryptfs-run
lrwxr-xr-x 1 root   shell           4 2008-12-31 16:30 egrep -> grep
-rwxr-xr-x 1 root   shell      261792 2008-12-31 16:30 emdlogger1
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 env -> toybox
-rwxr-xr-x 1 root   shell      423376 2008-12-31 16:30 exfatck
-rwxr-xr-x 1 root   shell      325072 2008-12-31 16:30 exfatdebug
-rwxr-xr-x 1 root   shell      312784 2008-12-31 16:30 exfatlabel
-rwxr-xr-x 1 root   shell      312784 2008-12-31 16:30 exfatvsn
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 expand -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 expr -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 fallocate -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 false -> toybox
lrwxr-xr-x 1 root   shell           4 2008-12-31 16:30 fgrep -> grep
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 file -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 find -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 flock -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 free -> toybox
-rwxr-xr-x 1 root   shell       97784 2008-12-31 16:30 fsck.f2fs
-rwxr-xr-x 1 root   shell       89888 2008-12-31 16:30 fsck_msdos
-rwxr-xr-x 1 root   shell       38752 2008-12-31 16:30 gatekeeperd
-rwxr-xr-x 1 root   shell       24672 2008-12-31 16:30 ged_srv
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 getenforce -> toybox
lrwxr-xr-x 1 root   shell           7 2008-12-31 16:30 getevent -> toolbox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 getprop -> toybox
-rwxr-xr-x 1 root   shell       29808 2008-12-31 16:30 grep
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 groups -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 gunzip -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 gzip -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 head -> toybox
-rwxr-xr-x 1 root   shell       52024 2008-12-31 16:30 healthd
-rwxr-xr-x 1 root   shell         213 2008-12-31 16:30 hid
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 hostname -> toybox
drwxr-xr-x 2 root   shell        4096 2008-12-31 16:30 hw
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 hwclock -> toybox
-rwxr-xr-x 1 root   shell       73624 2008-12-31 16:30 hwservicemanager
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 id -> toybox
-rwxr-xr-x 1 root   shell       37420 2008-12-31 16:30 idmaplrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ifconfig -> toybox
-rwxr-xr-x 1 root   shell         194 2008-12-31 16:30 ime
-rwxr-xr-x 1 root   shell       29080 2008-12-31 16:30 incident
-rwxr-xr-x 1 root   shell       51388 2008-12-31 16:30 incidentd
-rwxr-xr-x 1 root   shell         106 2008-12-31 16:30 info2presslog.sh
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 inotifyd -> toybox
-rwxr-xr-x 1 root   shell         203 2008-12-31 16:30 inputlrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 insmod -> toybox
-rwxr-x--- 1 root   root          694 2008-12-31 16:30 install-recovery.sh
-rwxr-xr-x 1 root   shell      209324 2008-12-31 16:30 installd
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ionice -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 iorenice -> toybox
-rwxr-xr-x 1 root   shell      224636 2008-12-31 16:30 ip
lrwxr-xr-x 1 root   shell          20 2008-12-31 16:30 ip-wrapper-1.0 -> netutils-wrapper-1.0
-rwxr-xr-x 1 root   shell      296604 2008-12-31 16:30 ip6tables
lrwxr-xr-x 1 root   shell           9 2008-12-31 16:30 ip6tables-restore -> ip6tables
lrwxr-xr-x 1 root   shell           9 2008-12-31 16:30 ip6tables-save -> ip6tables
lrwxr-xr-x 1 root   shell          20 2008-12-31 16:30 ip6tables-wrapper-1.0 -> netutils-wrapper-1.0
-rwxr-xr-x 1 root   shell        7607 2008-12-31 16:30 ipsec-rwxr-xr-x 1 root   shell       33800 2008-12-31 16:30 ipsecclient
-rwxr-xr-x 1 root   shell       94204 2008-12-31 16:30 ipsecd
-rwxr-xr-x 1 root   shell       16344 2008-12-31 16:30 ipsecstarter
-rwxr-xr-x 1 root   shell      287620 2008-12-31 16:30 iptables
lrwxr-xr-x 1 root   shell           8 2008-12-31 16:30 iptables-restore -> iptables
lrwxr-xr-x 1 root   shell           8 2008-12-31 16:30 iptables-save -> iptables
lrwxr-xr-x 1 root   shell          20 2008-12-31 16:30 iptables-wrapper-1.0 -> netutils-wrapper-1.0
-rwxr-xr-x 1 root   shell       16404 2008-12-31 16:30 kernel_logger
-rwxr-xr-x 1 root   shell       29124 2008-12-31 16:30 keyctl
-rwxr-xr-x 1 root   shell      162260 2008-12-31 16:30 keystore
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 kill -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 killall -> toybox
-rwxr-xr-x 1 root   shell       20500 2008-12-31 16:30 lcdc_screen_cap
-rwxr-xr-x 1 root   shell      472292 2008-12-31 16:30 ld.mc-rwxr-xr-x 1 root   shell       59480 2008-12-31 16:30 lgdrmserver
-rwxr-xr-x 1 root   shell       38724 2008-12-31 16:30 lghealthd
-rwxr-xr-x 1 root   shell       16328 2008-12-31 16:30 lgkmd-rwxr-xr-x 1 root   shell       16340 2008-12-31 16:30 lgkmd_soong
-rwxr-xr-x 1 root   shell       16184 2008-12-31 16:30 lgsecclkserver
-rwxr-xr-x 1 root   shell      259612 2008-12-31 16:30 lgtar-rwxr-xr-x 1 root   shell      847120 2008-12-31 16:30 linker
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 linker_asan -> linker
-rwxr-xr-x 1 root   shell       24860 2008-12-31 16:30 lmkd
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ln -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 load_policy -> toybox
-rwxr-xr-x 1 root   shell         194 2008-12-31 16:30 locksettings
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 log -> toybox
-rwxr-xr-x 1 root   shell       16200 2008-12-31 16:30 logcat
-rwxr-xr-x 1 root   shell        1752 2008-12-31 16:30 logger_events.sh
-rwxr-xr-x 1 root   shell        4213 2008-12-31 16:30 logger_kernel.sh
-rwxr-xr-x 1 root   shell        1903 2008-12-31 16:30 logger_main.sh
-rwxr-xr-x 1 root   shell         889 2008-12-31 16:30 logger_memory.sh
-rwxr-xr-x 1 root   shell         952 2008-12-31 16:30 logger_packet.sh
-rwxr-xr-x 1 root   shell        1611 2008-12-31 16:30 logger_power.sh
-rwxr-xr-x 1 root   shell        1747 2008-12-31 16:30 logger_radio.sh
-rwxr-xr-x 1 root   shell         375 2008-12-31 16:30 logger_setupwizard.sh
-rwxr-xr-x 1 root   shell        1958 2008-12-31 16:30 logger_system.sh
-rwxr-xr-x 1 root   shell         677 2008-12-31 16:30 logger_xfrm.sh
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 logname -> toybox
-rwxr-xr-x 1 root   shell       64596 2008-12-31 16:30 logwrapper
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 losetup -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ls -> toybox
-rwxr-xr-x 1 root   shell       16196 2008-12-31 16:30 lshallrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 lsmod -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 lsof -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 lspci -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 lsusb -> toybox
-rwxr-xr-x 1 root   shell       20324 2008-12-31 16:30 make_ext4fs
-rwxr-xr-x 1 root   shell       45896 2008-12-31 16:30 make_f2fs
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 md5sum -> toybox
-rwxr-xr-x 1 root   shell      328492 2008-12-31 16:30 md_monitor
-rwxr-xr-x 1 root   shell      183012 2008-12-31 16:30 md_monitor_ctrl
-rwxr-xr-x 1 root   shell    27398552 2008-12-31 16:30 mdi_redirector
-rwxr-xr-x 1 root   shell       34676 2008-12-31 16:30 mdi_redirector_ctrl
-rwxr-xr-x 1 root   shell      140304 2008-12-31 16:30 mdlogger
-rwxr-xr-x 1 root   shell      754796 2008-12-31 16:30 mdnsd-rwxr-xr-x 1 root   shell         210 2008-12-31 16:30 media-rwxr-xr-x 1 root   shell       24848 2008-12-31 16:30 mediadrmserver
-rwxr-xr-x 1 root   shell       20412 2008-12-31 16:30 mediaextractor
-rwxr-xr-x 1 root   shell       46876 2008-12-31 16:30 mediametrics
-rwxr-xr-x 1 root   shell       16324 2008-12-31 16:30 mediaserver
-rwxr-xr-x 1 root   shell       46436 2008-12-31 16:30 memory_logger
-rwxr-xr-x 1 root   shell      303080 2008-12-31 16:30 met-cmd
-rwxr-xr-x 1 root   shell      313716 2008-12-31 16:30 meta_tst
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 microcom -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mkdir -> toybox
-rwxr-xr-x 1 root   shell       74464 2008-12-31 16:30 mke2fs
-rwxr-xr-x 1 root   shell      353760 2008-12-31 16:30 mkexfat
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mkfifo -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mknod -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mkswap -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mktemp -> toybox
-rwxr-xr-x 1 root   shell       72712 2008-12-31 16:30 mobile_log_d
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 modinfo -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 modprobe -> toybox
-rwxr-xr-x 1 root   shell         268 2008-12-31 16:30 monkey
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 more -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mount -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mountpoint -> toybox
-rwxr-xr-x 1 root   shell       29108 2008-12-31 16:30 mtpd
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 mv -> toybox
-rwxr-xr-x 1 root   shell       16252 2008-12-31 16:30 ndc
lrwxr-xr-x 1 root   shell          20 2008-12-31 16:30 ndc-wrapper-1.0 -> netutils-wrapper-1.0
-rwxr-xr-x 1 root   shell      413076 2008-12-31 16:30 netd
-rwxr-xr-x 1 root   shell       63028 2008-12-31 16:30 netdiag
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 netstat -> toybox
-rwxr-xr-x 1 root   shell       50660 2008-12-31 16:30 netutils-wrapper-1.0
lrwxr-xr-x 1 root   shell           7 2008-12-31 16:30 newfs_msdos -> toolbox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 nice -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 nl -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 nohup -> toybox
-rwxr-xr-x 1 root   shell      189428 2008-12-31 16:30 oatdump
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 od -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 paste -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 patch -> toybox
-rwxr-xr-x 1 root   shell       54656 2008-12-31 16:30 patchoat
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 pgrep -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 pidof -> toybox
-rwxr-xr-x 1 root   shell       41876 2008-12-31 16:30 ping
-rwxr-xr-x 1 root   shell       46540 2008-12-31 16:30 ping6lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 pkill -> toybox
-rwxr-xr-x 1 root   shell         191 2008-12-31 16:30 pm
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 pmap -> toybox
-rwxr-xr-x 1 root   shell       16480 2008-12-31 16:30 power_logger
-rwxr-xr-x 1 root   shell      181636 2008-12-31 16:30 pppd
-rwxr-xr-x 1 root   shell       20516 2008-12-31 16:30 presslog
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 printenv -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 printf -> toybox
-rwxr-xr-x 1 root   shell       79880 2008-12-31 16:30 profman
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ps -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 pwd -> toybox
-rwxr-xr-x 1 root   shell      190972 2008-12-31 16:30 racoon
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 readlink -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 realpath -> toybox
-rwxr-xr-x 1 root   shell       16196 2008-12-31 16:30 reboot
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 renice -> toybox
-rwxr-xr-x 1 root   shell         188 2008-12-31 16:30 requestsync
-rwxr-xr-x 1 root   shell       58088 2008-12-31 16:30 resize2fs
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 restorecon -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 rm -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 rmdir -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 rmmod -> toybox
-rwxr-xr-x 1 root   shell       13736 2008-12-31 16:30 rtt
-rwxr-x--- 1 root   shell       20368 2008-12-31 16:30 run-as
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 runcon -> toybox
-rwxr-xr-x 1 root   shell       16184 2008-12-31 16:30 schedtest
-rwxr-xr-x 1 root   shell       20468 2008-12-31 16:30 screencap
-rwxr-xr-x 1 root   shell      112484 2008-12-31 16:30 screenrecord
-rwxr-xr-x 1 root   shell       45960 2008-12-31 16:30 sdcard
-rwxr-xr-x 1 root   shell       28944 2008-12-31 16:30 secdiscard
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sed -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sendevent -> toybox
-rwxr-xr-x 1 root   shell       16264 2008-12-31 16:30 sensorservice
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 seq -> toybox
-rwxr-xr-x 1 root   shell       37356 2008-12-31 16:30 service
-rwxr-xr-x 1 root   shell       20940 2008-12-31 16:30 servicemanager
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 setenforce -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 setprop -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 setsid -> toybox
-rwxr-xr-x 1 root   shell          35 2008-12-31 16:30 settings
-rwxr-xr-x 1 root   shell       16300 2008-12-31 16:30 setup_fs
-rwxr-xr-x 1 root   shell      121288 2008-12-31 16:30 sgdisk
-rwxr-xr-x 1 root   shell      200104 2008-12-31 16:30 sh
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sha1sum -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sha224sum -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sha256sum -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sha384sum -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sha512sum -> toybox
-rwxr-xr-x 1 root   shell       67936 2008-12-31 16:30 shutdownanimation
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sleep -> toybox
-rwxr-xr-x 1 root   shell      110344 2008-12-31 16:30 sload_f2fs
-rwxr-xr-x 1 root   shell         190 2008-12-31 16:30 sm
-rwxr-xr-x 1 root   shell       16264 2008-12-31 16:30 sn
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sort -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 split -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 start -> toybox
-rwxr-xr-x 1 root   shell       70944 2008-12-31 16:30 starter
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 stat -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 stop -> toybox
-rwxr-xr-x 1 root   shell       93956 2008-12-31 16:30 storaged
-rwxr-xr-x 1 root   shell       24800 2008-12-31 16:30 storagemanagerd
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 strings -> toybox
-rwxr-xr-x 1 root   shell       24528 2008-12-31 16:30 stroke
-rwxr-xr-x 1 root   shell         192 2008-12-31 16:30 svc
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 swapoff -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 swapon -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sync -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 sysctl -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tac -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tail -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tar -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 taskset -> toybox
-rwxr-xr-x 1 root   shell       92548 2008-12-31 16:30 tc
lrwxr-xr-x 1 root   shell          20 2008-12-31 16:30 tc-wrapper-1.0 -> netutils-wrapper-1.0
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tee -> toybox
-rwxr-xr-x 1 root   shell         172 2008-12-31 16:30 telecom
-rwxr-xr-x 1 root   shell       16236 2008-12-31 16:30 terservice
-rwxr-xr-x 1 root   shell       16208 2008-12-31 16:30 tertestclient
-rwxr-xr-x 1 root   shell       20388 2008-12-31 16:30 thermald
-rwxr-xr-x 1 root   shell       24744 2008-12-31 16:30 thermalindicator
-rwxr-xr-x 1 root   shell       33736 2008-12-31 16:30 thermalserviced
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 time -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 timeout -> toybox
-rwxr-xr-x 1 root   shell      126068 2008-12-31 16:30 tombstoned
-rwxr-xr-x 1 root   shell       72240 2008-12-31 16:30 toolbox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 top -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 touch -> toybox
-rwxr-xr-x 1 root   shell      331628 2008-12-31 16:30 toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tr -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 true -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 truncate -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 tty -> toybox
-rwxr-xr-x 1 root   shell       57820 2008-12-31 16:30 tune2fs
-rwxr-xr-x 1 root   shell       28896 2008-12-31 16:30 tzdatacheck
-rwxr-xr-x 1 root   shell        4156 2008-12-31 16:30 uiautomator
-rwxr-xr-x 1 root   shell        3991 2008-12-31 16:30 uiautomatorLG
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 ulimit -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 umount -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 uname -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 uniq -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 unix2dos -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 uptime -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 usleep -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 uudecode -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 uuencode -> toybox
-rwxr-xr-x 1 root   shell       24708 2008-12-31 16:30 vdc
-rwxr-xr-x 1 root   shell       24616 2008-12-31 16:30 vintflrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 vmstat -> toybox
-rwxr-xr-x 1 root   shell      581664 2008-12-31 16:30 vold
-rwxr-xr-x 1 root   shell         152 2008-12-31 16:30 vr
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 wc -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 which -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 whoami -> toybox
-rwxr-xr-x 1 root   shell      212652 2008-12-31 16:30 wificond
-rwxr-xr-x 1 root   shell         190 2008-12-31 16:30 wm
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 xargs -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 xxd -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 yes -> toybox
lrwxr-xr-x 1 root   shell           6 2008-12-31 16:30 zcat -> toybox
mlv7:/ $

**Comment by dstmaloka** [comment]
I have the same problem

**Comment by JunioJsv** [comment]
Attempts to delete Magisk Manager and reinstall version 7.1.1 of it
