### ISSUE TITLE
[✅] Lenovo A5 l18021 (official). Android 8.1.0. MT6739. Works.

### ISSUE THREAD

**Issue by N08I40K** [JunioJsv/mtk-easy-su#122]
State: ✅.
Model: Lenovo A5 (l18021) Official build.
Android version:  8.1.0.
MTK: MT6739.
Bootloader: Password-locked.

This app works!
Many thanks to the authors.
I haven't been able to get root rights on my phone for more than a year and a half (Password-locked bootloader).

**Comment by Dim3333** [comment]
Hi @N08I40K,

I'm interesting to root my LENOVO A5. Could you help me to do that ? Do you know a tutorial ?

Thanks.
