### ISSUE TITLE
Magisk Unsupported Su

### ISSUE THREAD

**Issue by santyboy007** [JunioJsv/mtk-easy-su#129]
How fix this?
Abnormal State
An "su" command that does no belong to Magisk is detected. Please remove the other unsupported su

**Comment by A5H1Q** [comment]
same issue here.. any leads?

**Comment by A5H1Q** [comment]
Thanks to this [article](https://min.news/en/digital/1c4b3c8793484d5569a5a6defcb06ee9.html), I've managed to fix the issue. the solution was to rename the ```su``` file located in ```/system/xbin``` directory. I used root explorer (ver 4.1.4 by speed software) for renaming the system file. hope this helps 👍🏻

**Comment by Karthikeya69** [comment]
what to rename bro can u tell me in detail

**Comment by A5H1Q** [comment]
> what to rename bro can u tell me in detail

Anything other than su, maybe su2

**Comment by Pika3pika** [comment]
can't rename, the file is read only, how can i change file permissions

**Comment by XJIOP** [comment]
> can't rename, the file is read only, how can i change file permissions

Simply remount as rw (Read/Write):
`mount -o rw,remount /system`

Once you are done making changes, remount to ro (read-only):
`mount -o ro,remount /system`
