### ISSUE TITLE
Support mtk MT6570

### ISSUE THREAD

**Issue by deleteBlack666** [JunioJsv/mtk-easy-su#132]
hello developers!
Can add support for mtk 6750 please! Want to test
I tried getting root but error: Mtk-easy-su 2.0.6
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0] 

[0] 6.0

[0] Sat Jun 19 20:47:50 MSK 2021

[1] ls: Unknown option '-1'. Aborting.

[0] Processor : ARMv7 Processor rev 3 (v7l)
processor : 0
model name : ARMv7 Processor rev 3 (v7l)
BogoMIPS : 33.76
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part : 0xc07
CPU revision : 3

processor : 1
model name : ARMv7 Processor rev 3 (v7l)
BogoMIPS : 33.76
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part : 0xc07
CPU revision : 3

Hardware : MT6570
Revision : 0000
Serial 	    : 0000000000000000

[0] MemTotal:         474344 kB
MemFree:            7452 kB
MemAvailable:     203624 kB
Buffers:            6204 kB
Cached:           189668 kB
SwapCached:        23184 kB
Active:           164040 kB
Inactive:         164600 kB
Active(anon):      67604 kB
Inactive(anon):    70512 kB
Active(file):      96436 kB
Inactive(file):    94088 kB
Unevictable:        2268 kB
Mlocked:               0 kB
HighTotal:             0 kB
HighFree:              0 kB
LowTotal:         474344 kB
LowFree:            7452 kB
SwapTotal:        355756 kB
SwapFree:         263528 kB
Dirty:               888 kB
Writeback:             0 kB
AnonPages:        126320 kB
Mapped:            89340 kB
Shmem:              3076 kB
Slab:              56684 kB
SReclaimable:      16736 kB
SUnreclaim:        39948 kB
KernelStack:        7008 kB
PageTables:        11244 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      592928 kB
Committed_AS:   15714028 kB
VmallocTotal:     507904 kB
VmallocUsed:       62960 kB
VmallocChunk:     377784 kB

[0]  	    total        used        free      shared     buffers
Mem:        485728256   478126080     7602176     3149824     6352896
-/+ buffers/cache:      471773184    13955072
Swap:       364294144    94441472   269852672

[0] Linux version 3.18.35 (ap-2-x7@ubuntux7) (gcc version 4.8 (GCC) ) #2 SMP PREEMPT Thu Jun 21 18:35:36 CST 2018

[1] Temporary root by diplomatic@XDA
Home URL:
[url="https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213"]https://forum.xda-deve…ediatek-armv8-t3922213[/url]
--------------------------------------------------

armv7l machine
param1: 0x1000, param2: 0x8040, type: 4
Building symbol table
Can't find kallsyms addresses or offsets
Unable to get kernel symbol table
Error setting u:r:untrusted_app:s0 context: Permission denied
starting /system/bin/sh
UID: 10673  cap: 0000000000  selinux: enforcing  
Root user only

deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

**Comment by Hajisk** [comment]
Plij
