### ISSUE TITLE
Oppo Ch 1727 failed to root

### ISSUE THREAD

**Issue by Daenk7** [JunioJsv/mtk-easy-su#133]
Hi sir im failed root my phone can u help me

Failed critical init step 4
This firmware cannot be supported
Mtk-easy-su 2.0.6
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0] 

[0] 7.1.1

[0] Wed Jun 30 07:47:59 WIB 2021

[0] /data/user/0/juniojsv.mtk.easy.su/files:
total 12K
drwx------ 2 u0_a163 4.0K 2021-06-30 07:47 32
drwx------ 2 u0_a163 4.0K 2021-06-30 07:47 64
-r-x--x--- 1 u0_a163 2.8K 2021-06-30 07:47 magisk-boot.sh

/data/user/0/juniojsv.mtk.easy.su/files/32:
total 436K
-r-x--x--- 1 u0_a163 373K 2021-06-30 07:47 magiskinit
-r-x--x--- 1 u0_a163  59K 2021-06-30 07:47 mtk-su

/data/user/0/juniojsv.mtk.easy.su/files/64:
total 460K
lrwxrwxrwx 1 u0_a163   10 2021-06-30 07:42 magisk -> magiskinit
-r-x--x--- 1 u0_a163 393K 2021-06-30 07:47 magiskinit
lrwxrwxrwx 1 u0_a163   10 2021-06-30 07:42 magiskpolicy -> magiskinit
-r-x--x--- 1 u0_a163  64K 2021-06-30 07:47 mtk-su

[0] Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
model name	: AArch64 Processor rev 4 (aarch64)
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: MT6763V/CT

[0] MemTotal:        5935072 kB
MemFree:          475412 kB
MemAvailable:    2653224 kB
Buffers:           30240 kB
Cached:          2517936 kB
SwapCached:       112300 kB
Active:          2185284 kB
Inactive:        1648800 kB
Active(anon):     631928 kB
Inactive(anon):   688008 kB
Active(file):    1553356 kB
Inactive(file):   960792 kB
Unevictable:        6764 kB
Mlocked:             272 kB
SwapTotal:       2621436 kB
SwapFree:        1701216 kB
Dirty:               716 kB
Writeback:             0 kB
AnonPages:       1264100 kB
Mapped:          1313568 kB
Shmem:             27516 kB
Slab:             385372 kB
SReclaimable:     276172 kB
SUnreclaim:       109200 kB
KernelStack:       52336 kB
PageTables:        73680 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     5588972 kB
Committed_AS:   147348532 kB
VmallocTotal:   258867136 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
CmaTotal:        4190208 kB
CmaFree:          231076 kB
Oppo0Free:             0 kB
Oppo2Free:         31296 kB
IonTotalCache:    172080 kB
IonTotalUsed:     110272 kB

[0] 		total        used        free      shared     buffers
Mem:       6077513728  5590691840   486821888    28176384    30965760
-/+ buffers/cache:     5559726080   517787648
Swap:      2684350464   942305280  1742045184

[0] Linux version 4.4.22+ (root@ubuntu16-30-35) (gcc version 4.9 20150123 (prerelease) (GCC) ) #4 SMP PREEMPT Thu Sep 3 23:42:08 CST 2020

[1] Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

Failed critical init step 4
This firmware cannot be supported

deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

**Comment by ClientBeta** [comment]
So Ur phone is in Expert root mode so it requires recovery IMG or something on magisk

**Comment by alvansC** [comment]
What do you mean by in expert root mode and recovery IMG? i also failed on step 4, my model is oppo cph1723 can u help?

**Comment by NeonzGamingYT** [comment]
> What do you mean by in expert root mode and recovery IMG? i also failed on step 4, my model is oppo cph1723 can u help?

as i know there is someone with OPPO F5 too successfully rooted his device using this

**Comment by NeonzGamingYT** [comment]
im also getting that error on my OPPO F5 6GB CPH1727

**Comment by Veshurik** [comment]
I also want to know how to root this model (CPH1723). 
That's terrible that it doesn't work.
