### ISSUE TITLE
How to fix Redmi note 10s MIUI GLOBAL 12.5.11 Can't open mtk easy su

### ISSUE THREAD

**Issue by Jokeritloog** [JunioJsv/mtk-easy-su#138]
How to fix Redmi note 10s MIUI GLOBAL 12.5.11 Can't open mtk easy su

**Comment by Jokeritloog** [comment]
> How to fix Redmi note 10s MIUI GLOBAL 12.5.11 Can't open mtk easy su
Automatic closing

**Comment by JunioJsv** [comment]
sorry, pls try on latest version v2.1.0
