### ISSUE TITLE
CPH1853 error output root installation (expert)

### ISSUE THREAD

**Issue by ClientBeta** [JunioJsv/mtk-easy-su#144]
Root installation : Expert

Output of easy Su : Mtk-easy-su 2.0.6
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0] CPH1853

[0] 8.1.0

[0] Thu Sep 30 21:02:18 +08 2021

[0] /data/user/0/juniojsv.mtk.easy.su/files:
total 6.0K
drwx------ 2 u0_a1113 4.0K 2021-09-30 21:02 32
drwx------ 2 u0_a1113 4.0K 2021-09-30 21:02 64
-r-x--x--- 1 u0_a1113 2.8K 2021-09-30 21:02 magisk-boot.sh

/data/user/0/juniojsv.mtk.easy.su/files/32:
total 218K
lrwxrwxrwx 1 u0_a1113   10 2021-09-30 17:19 magisk -> magiskinit
-r-x--x--- 1 u0_a1113 373K 2021-09-30 21:02 magiskinit
lrwxrwxrwx 1 u0_a1113   10 2021-09-30 17:19 magiskpolicy -> magiskinit
-r-x--x--- 1 u0_a1113  59K 2021-09-30 21:02 mtk-su

/data/user/0/juniojsv.mtk.easy.su/files/64:
total 230K
lrwxrwxrwx 1 u0_a1113   10 2021-09-30 17:27 magisk -> magiskinit
-r-x--x--- 1 u0_a1113 393K 2021-09-30 21:02 magiskinit
lrwxrwxrwx 1 u0_a1113   10 2021-09-30 17:27 magiskpolicy -> magiskinit
-r-x--x--- 1 u0_a1113  64K 2021-09-30 21:02 mtk-su

[0] Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: Qualcomm Technologies, Inc SDM450

[0] MemTotal:        1844012 kB
MemFree:           46252 kB
MemAvailable:     713360 kB
Buffers:           24000 kB
Cached:           677700 kB
SwapCached:         9468 kB
Active:           522484 kB
Inactive:         523656 kB
Active(anon):     173248 kB
Inactive(anon):   174128 kB
Active(file):     349236 kB
Inactive(file):   349528 kB
Unevictable:         260 kB
Mlocked:             260 kB
SwapTotal:       1310716 kB
SwapFree:         657648 kB
Dirty:              1528 kB
Writeback:             0 kB
AnonPages:        342552 kB
Mapped:           339432 kB
Shmem:              2500 kB
Slab:             178352 kB
SReclaimable:      49508 kB
SUnreclaim:       128844 kB
KernelStack:       44608 kB
PageTables:        55484 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2232720 kB
Committed_AS:   92813152 kB
VmallocTotal:   263061440 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
CmaTotal:         245760 kB
CmaFree:             592 kB
Oppo2Free:           128 kB
IonTotalCache:      7328 kB
IonTotalUsed:      37236 kB

[0] 		total        used        free      shared     buffers
Mem:       1888268288  1841143808    47124480     2560000    24576000
-/+ buffers/cache:     1816567808    71700480
Swap:      1342173184   668741632   673431552

[1] cat: /proc/version: Permission denied

[1] Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv8l machine
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

Failed critical init step 1
Incompatible platform

deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

**Comment by NeonzGamingYT** [comment]
Sorry but this is for "Mediatek" Only, not Snapdragon
