### ISSUE TITLE
Busybox cannot be install on system/bin using this root

### ISSUE THREAD

**Issue by HoaxSnowden18** [JunioJsv/mtk-easy-su#15]
It says installation was not successful everytime i install busybox on system/bin.

**Comment by JunioJsv** [comment]
try install on /system/xbin or in /data/ temp folder

**Comment by uzeda4** [comment]
Try to install on the /sbin, i did and it worked. However you need to mark an option to reinstall the busybox on every boot on the /sbin, because on the /sbin gets wiped out on every boot.

**Comment by JunioJsv** [comment]
try installing using the magisk manager module
