### ISSUE TITLE
Revvl 5 : Model: TMRVL4G - Crash on app launch

### ISSUE THREAD

**Issue by unicxa** [JunioJsv/mtk-easy-su#150]
Cannot open app on Revvl 5.
Here is my device specs:

Brand:
T-Mobile

Manufacturer:
Wingtech

Product:
Newcastle

Model:
TMRVL4G

Android Version:
Android 11

Minimum Target SDK:
23

Build Number:
TMRVL4G_0.03.25

Board:
S98117AA1

Hardware:
mt6762

**Comment by JunioJsv** [comment]
Try on latest version 2.1.0

**Comment by adeljmking** [comment]
Please need firmware TMRVL4G_0.03.25
