### ISSUE TITLE
Mt6735m . Bootloader

### ISSUE THREAD

**Issue by barbaraskar** [JunioJsv/mtk-easy-su#152]
I have old 2016 Huawei y 3 II 
I want to root it 
I tried all ways but zero success .
Is it possible to unlock the bootloader using your code? And dawnload new recovery ? Like twrp recovery?

**Comment by fabian222005** [comment]
I'm not responsible of misuse or bricked phones. 
Try using the TWRP recovery app, and flash your recovery. Don't forget to backup the existing recovery. I'm not responsible of misuse or bricked phones.
