### ISSUE TITLE
GEELY preface E01

### ISSUE THREAD

**Issue by happy999day** [JunioJsv/mtk-easy-su#154]
Mtk-easy-su 2.0.6
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0]
[0] 5.1
[0] Sun Mar 13 06:53:17 CST 2022
[1] ls: Unknown option '-1'. Aborting.
[0] Processor : AArch64 Processor rev 3 (aarch64)
processor : 0
BogoMIPS : 26.00
processor : 1
BogoMIPS : 26.00
Features : fp asimd aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: AArch64
CPU variant : 0x0
CPU part : 0xd03
CPU revision : 3
Hardware : MT6735
[0] MemTotal:        1967280 kB
MemFree:           26044 kB
Buffers:            7864 kB
Cached:           379996 kB
SwapCached:          552 kB
Active:          1038808 kB
Inactive:         474276 kB
Active(anon):     848368 kB
Inactive(anon):   283096 kB
Active(file):     190440 kB
Inactive(file):   191180 kB
Unevictable:        2520 kB
Mlocked:               0 kB
SwapTotal:        524284 kB
SwapFree:         481252 kB
Dirty:              1012 kB
Writeback:             0 kB
AnonPages:       1127448 kB
Mapped:           217464 kB
Shmem:              3628 kB
Slab:              95636 kB
SReclaimable:      37036 kB
SUnreclaim:        58600 kB
KernelStack:       40960 kB
PageTables:        47296 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1507924 kB
Committed_AS:   77266620 kB
VmallocTotal:   251658176 kB
VmallocUsed:      171012 kB
VmallocChunk:   251410196 kB
Error running exec(). Command: [free] Working Directory: null Environment: null[0] Linux version 3.10.65+ (gitadmin@gitadmin-server) (gcc version 4.9.x-google 20140827 (mtk-20150409) (GCC) ) #1 SMP PREEMPT Wed Jun 9 14:14:29 CST 2021
[1] /data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[13]: dirname: not found
/data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[113]: cd: /32: No such file or directory
deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

**Comment by Chipsnet** [comment]
I had the same problem and was able to solve it.
See comments below.
https://github.com/JunioJsv/mtk-easy-su/issues/163#issuecomment-1140455440
