### ISSUE TITLE
dirname:not found

### ISSUE THREAD

**Issue by 0xlo0p** [JunioJsv/mtk-easy-su#163]
Mtk-easy-su 2.1.0
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0] 

[0] 5.1.1

[0] Fri May 13 00:49:15 CST 2022

[1] ls: Unknown option '-1'. Aborting.

[0] processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 2
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: Qualcomm Technologies, Inc MSM8909
Revision	: 0000
Serial		: 0000000000000000
Processor	: ARMv7 Processor rev 5 (v7l)

[0] MemTotal:         923240 kB
MemFree:           62548 kB
Buffers:            2812 kB
Cached:           267948 kB
SwapCached:          464 kB
Active:           292876 kB
Inactive:         279016 kB
Active(anon):     158772 kB
Inactive(anon):   149376 kB
Active(file):     134104 kB
Inactive(file):   129640 kB
Unevictable:        1324 kB
Mlocked:               0 kB
HighTotal:        270336 kB
HighFree:           3632 kB
LowTotal:         652904 kB
LowFree:           58916 kB
SwapTotal:        524284 kB
SwapFree:         422256 kB
Dirty:               740 kB
Writeback:             0 kB
AnonPages:        302272 kB
Mapped:           208520 kB
Shmem:              5608 kB
Slab:              38856 kB
SReclaimable:      11588 kB
SUnreclaim:        27268 kB
KernelStack:       10872 kB
PageTables:        20056 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      985904 kB
Committed_AS:   30830352 kB
VmallocTotal:     245760 kB
VmallocUsed:       84820 kB
VmallocChunk:      67380 kB

Error running exec(). Command: [free] Working Directory: null Environment: null[0] Linux version 3.10.49-svn105 (liuqifeng@chainway-PowerEdge-R730) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Wed Aug 26 10:39:39 CST 2020

**[1] /data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[13]: dirname: not found
/data/data/juniojsv.mtk.easy.su/files/magisk-boot.sh[113]: cd: /32: No such file or directory**

deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

How can I solve this，Thx

**Comment by 0xlo0p** [comment]
I had tried in x64 and x32 mode both

**Comment by Chipsnet** [comment]
Are you running on an Android 5.x smartphone?
This application cannot be run on Android 5.x.

This application is designed to run mtk-su easily, but it can be run on Android 5.x by running mtk-su directly.

Please refer to the following XDA post to run it.
https://forum.xda-developers.com/t/amazing-temp-root-for-mediatek-armv8-2020-08-24.3922213/page-50#post-82081703

However, for Android 5.x, you need to use the following Magisk boot script
https://forum.xda-developers.com/t/rapid-temporary-root-for-hd-8-hd-10.3904595/post-82731447

Hope this post helps you!

Translated with www.DeepL.com/Translator (free version)
