### ISSUE TITLE
Clarifications before i root

### ISSUE THREAD

**Issue by jtfoss** [JunioJsv/mtk-easy-su#178]
I have an CPH1717, and luckily the security patch level is on 2019, so it *should* work.
Before i root though, i just want to make out clarifications.
Will this only give out temporary root, or permanent root? Just asking as this is the only personal device I have under my ownership and I can't afford to lose this one by just bricking.

Thanks for this project, though.

**Comment by JunioJsv** [comment]
it's only temporary, after restarting the device root access will be lost, if you don't know what you're doing it's better not to try, with root access you can ruin your device's system easily
