### ISSUE TITLE
Oppo F11 Pro Mediatek but it can't be root Need Help Seniors 

### ISSUE THREAD

**Issue by basharatr77** [JunioJsv/mtk-easy-su#181]
Mtk-easy-su 2.1.1
extracted magisk-boot.sh
extracted 32/magiskinit
extracted 64/magiskinit
extracted 32/mtk-su
extracted 64/mtk-su
[0] 

[0] 11

[0] Wed Dec 14 23:59:43 PKT 2022

[0] /data/user/0/juniojsv.mtk.easy.su/files:
total 18K
drwx------ 2 u0_a301 4.0K 2022-12-14 23:59 32
drwx------ 2 u0_a301 4.0K 2022-12-14 23:59 64
-rw------- 1 u0_a301  566 2022-12-14 23:39 PersistedInstallation.W0RFRkFVTFRd+MTo2OTczNzY1NDAxNDphbmRyb2lkOjIzZGMwMWQyYTRjOWQzYmY2ZjI3YWY.json
-rw------- 1 u0_a301    0 2022-12-14 23:39 generatefid.lock
-r-x--x--- 1 u0_a301 2.8K 2022-12-14 23:59 magisk-boot.sh

/data/user/0/juniojsv.mtk.easy.su/files/32:
total 226K
lrwxrwxrwx 1 u0_a301   18 2022-12-14 23:41 magisk -> magiskinit
-r-x--x--- 1 u0_a301 373K 2022-12-14 23:59 magiskinit
lrwxrwxrwx 1 u0_a301   18 2022-12-14 23:41 magiskpolicy -> magiskinit
-r-x--x--- 1 u0_a301  59K 2022-12-14 23:59 mtk-su

/data/user/0/juniojsv.mtk.easy.su/files/64:
total 238K
lrwxrwxrwx 1 u0_a301   18 2022-12-14 23:55 magisk -> magiskinit
-r-x--x--- 1 u0_a301 393K 2022-12-14 23:59 magiskinit
lrwxrwxrwx 1 u0_a301   18 2022-12-14 23:55 magiskpolicy -> magiskinit
-r-x--x--- 1 u0_a301  64K 2022-12-14 23:59 mtk-su

[0] processor	: 0
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 5
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 6
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 7
BogoMIPS	: 26.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

Hardware	: MT6771V/WT

[0] MemTotal:        5787836 kB
MemFree:          234452 kB
MemAvailable:    2249052 kB
Buffers:           98052 kB
Cached:          2136644 kB
SwapCached:        66772 kB
Active:          2399436 kB
Inactive:        1594944 kB
Active(anon):    1066448 kB
Inactive(anon):   893936 kB
Active(file):    1332988 kB
Inactive(file):   701008 kB
Unevictable:      177700 kB
Mlocked:          177724 kB
SwapTotal:       3145724 kB
SwapFree:        2226940 kB
Dirty:              1012 kB
Writeback:           532 kB
AnonPages:       1926308 kB
Mapped:          1368896 kB
Shmem:             28128 kB
KReclaimable:     235048 kB
Slab:             237172 kB
SReclaimable:      55664 kB
SUnreclaim:       181508 kB
KernelStack:       77008 kB
PageTables:       111128 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6039640 kB
Committed_AS:   120792276 kB
VmallocTotal:   263061440 kB
VmallocUsed:      153908 kB
VmallocChunk:          0 kB
CmaTotal:         327680 kB
CmaFree:          138800 kB
IonTotalCache:    179384 kB
IonTotalUsed:     203448 kB

[0] 		total        used        free      shared     buffers
Mem:       5926744064  5682126848   244617216    28815360   100405248
-/+ buffers/cache:     5581721600   345022464
Swap:      3221221376   940834816  2280386560

[1] cat: /proc/version: Permission denied

[1] /data/user/0/juniojsv.mtk.easy.su/files/magisk-boot.sh[124]: ./mtk-su: Permission denied

deleted magisk-boot.sh
deleted 32/magiskinit
deleted 64/magiskinit
deleted 32/mtk-su
deleted 64/mtk-su

**Comment by rollingmoai** [comment]
Use [mtkclient](https://github.com/bkerler/mtkclient) and follow the instructions in the readme for successful root
