### ISSUE TITLE
Magisk modules

### ISSUE THREAD

**Issue by LucianoNeo** [JunioJsv/mtk-easy-su#183]
Why I cant install any magisk module? 
I got an error :
PLEASE INSTALL MAGISK V20.4+!

But I'm already using this version
Magisk installed : 21.4
Magisk manager: 8.0.4

**Comment by BinhChuAi** [comment]
you again install magisk 20.4

**Comment by LucianoNeo** [comment]
How can I do that? Cause mtk install magisk 21.4 not 20.4...

**Comment by BinhChuAi** [comment]
hmm sorry, video ?
