### ISSUE TITLE
Busybox

### ISSUE THREAD

**Issue by saretto28** [JunioJsv/mtk-easy-su#19]
Yesterday I tried to use Lucky patcher but it requires busybox I also tried to install busybox but can not find a way?

**Comment by uzeda4** [comment]
Try to install on the /sbin, i did and it worked. However you need to mark an option to reinstall the busybox on every boot on the /sbin, because on the /sbin gets wiped out on every boot.

**Comment by JunioJsv** [comment]
The best way to install busybox is using the magisk manager it installs a static version that does not come out when restarting the phone

**Comment by JunioJsv** [comment]
![Screenshot_2020-01-29-21-04-32](https://user-images.githubusercontent.com/39963398/73408431-fccfc500-42da-11ea-979f-35c20b27b737.png) it
