### ISSUE TITLE
Realme C25y (stuck)

### ISSUE THREAD

**Issue by jems2003-lang** [JunioJsv/mtk-easy-su#201]
I can't proceed to the next procedure since this instruction keeps popping up even though I already rebooted my device. Please help, I don't know what to do at this point. Am I missing something? I did the hard reset where I found the "_reboot system now_" and click, (I did this because my phone doesn't have a reboot option, only "restart and power off".

![Screenshot_20231223-173742](https://github.com/JunioJsv/mtk-easy-su/assets/154668511/586cbe6d-cc18-4d37-bfba-870e64799cef)

**Comment by jems2003-lang** [comment]
Closed??? Why

**Comment by JunioJsv** [comment]
Try using a newer version
