### ISSUE TITLE
Magisk

### ISSUE THREAD

**Issue by saretto28** [JunioJsv/mtk-easy-su#21]
But will you be able to find a way to use any root app with magisk do I have a way to unlock the bootloader?  It was nice if you could change roms maybe what I'm saying is not feasible but at least thanks to you I can enjoy the root a bit like I did years ago ;)

It gives me this error:

- Copying zip to temp directory
- Installing Busybox_for_Android_NDK-1.31.1.zip
Archive:  /data/user/0/com.Ukx.i.SP5.eq95uV/cache/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.Ukx.i.SP5.eq95uV/cache/install.zip
  inflating: install.sh
  inflating: module.prop
 
Busybox Installer Script
by osm0sis @ xda-developers
 
Mounting...
mount: can't read '/etc/fstab': No such file or directory
mount: can't read '/etc/fstab': No such file or directory
mount: can't read '/etc/fstab': No such file or directory
 
Extracting files...
Archive:  /data/user/0/com.Ukx.i.SP5.eq95uV/cache/install.zip
   creating: META-INF/
   creating: META-INF/com/
   creating: META-INF/com/google/
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
  inflating: README.md
  inflating: busybox-arm
  inflating: busybox-arm64
  inflating: busybox-mips
  inflating: busybox-mips64
  inflating: busybox-x86
  inflating: busybox-x86_64
  inflating: install.sh
  inflating: module.prop
 
umount: can't unmount /dev/tmp/magisk: No such file or directory
mount: can't setup loop device: No such file or directory
mknod: /dev/block/loop0: File exists
mkdir: can't create directory '/dev/tmp/magisk/busybox-ndk/': Read-only file system
Installing...
Using architecture: arm64
cp: can't create '/dev/tmp/magisk/busybox-ndk/system/xbin/busybox': Path does not exist
chown: /dev/tmp/magisk/busybox-ndk/system/xbin/busybox: No such file or directory
Using path: /dev/tmp/magisk/busybox-ndk/system/xbin
chmod: /dev/tmp/magisk/busybox-ndk/system/xbin/busybox: No such file or directory
cp: can't create '/dev/tmp/magisk/busybox-ndk/': Is a directory
touch: /dev/tmp/magisk/busybox-ndk/auto_mount: No such file or directory
update-binary: cd: line 112: can't cd to /dev/tmp/magisk/busybox-ndk/system/xbin: No such file or directory
 
Cleaning...
update-binary: /dev/tmp/install.sh: line 113: /dev/tmp/magisk/busybox-ndk/system/xbin/busybox: not found
update-binary: /dev/tmp/install.sh: line 119: /dev/tmp/magisk/busybox-ndk/system/xbin/busybox: not found
 
Creating symlinks...
update-binary: /dev/tmp/install.sh: line 1: /dev/tmp/magisk/busybox-ndk/system/xbin/busybox: not found
chcon: /dev/tmp/magisk/busybox-ndk: No such file or directory
 
Unmounting...
umount: can't unmount /system: Device or resource busy
umount: can't unmount /data: Device or resource busy
umount: can't unmount /cache: Device or resource busy
 
Done!

**Comment by uzeda4** [comment]
Seeing that someone opened a topic for magisk, let me ask you something, do you plan on update the program to work with newer versions of Magisk?

**Comment by JunioJsv** [comment]
> Seeing that someone opened a topic for magisk, let me ask you something, do you plan on update the program to work with newer versions of Magisk?

it doesn’t depend on me, but on the Diplomatic developer of mtk-su, and incidentally I’m kind of out of time.

**Comment by saretto28** [comment]
> > Visto che qualcuno ha aperto un argomento per magisk, lascia che ti chieda una cosa, pensi di aggiornare il programma per lavorare con le versioni più recenti di Magisk?
> 
> non dipende da me, ma dallo sviluppatore diplomatico di mtk-su, e per inciso sono un po 'fuori tempo.

Do you know if there is a way to make gltools work with the ho module with the temporary root?

**Comment by JunioJsv** [comment]
> > > Visto che qualcuno ha aperto un argomento per magisk, lascia che ti chieda una cosa, pensi di aggiornare il programma per lavorare con le versioni più recenti di Magisk?
> > 
> > 
> > non dipende da me, ma dallo sviluppatore diplomatico di mtk-su, e per inciso sono un po 'fuori tempo.
> 
> Do you know if there is a way to make gltools work with the ho module with the temporary root?

I will try to install it here, if I followed it I will send it step by step in this issue

**Comment by saretto28** [comment]
> > > > Visto che qualcuno ha aperto un argomento per magisk, lascia che ti chieda una cosa, pensi di aggiornare il programma per lavorare con le versioni più recenti di Magisk?
> > > 
> > > 
> > > non dipende da me, ma dallo sviluppatore diplomatico di mtk-su, e per inciso sono un po 'fuori tempo.
> > 
> > 
> > Sai se esiste un modo per far funzionare gltools con il modulo ho con il root temporaneo?
> 
> Cercherò di installarlo qui, se l'ho seguito lo invierò passo dopo passo in questo problema

Thanks! ✌🏻

**Comment by aIecxs** [comment]
read carefully all warnings! not for noobs!
https://forum.xda-developers.com/showpost.php?p=79626434&postcount=135

**Comment by JunioJsv** [comment]
> read carefully all warnings! not for noobs!
> https://forum.xda-developers.com/showpost.php?p=79626434&postcount=135

obvious

**Comment by JunioJsv** [comment]
![Screenshot_2020-02-07-11-29-13](https://user-images.githubusercontent.com/39963398/74037536-3a001b00-499d-11ea-8a28-b22fbafb6857.png)
I managed to install the gltools module but for some reason it is not applying the settings

**Comment by saretto28** [comment]
> ![Screenshot_2020-02-07-11-29-13](https://user-images.githubusercontent.com/39963398/74037536-3a001b00-499d-11ea-8a28-b22fbafb6857.png)
> Sono riuscito a installare il modulo gltools ma per qualche motivo non applica le impostazioni

Do you think something can be done to apply the settings equally?

**Comment by saretto28** [comment]
> @ saretto28 leggi attentamente tutti gli avvisi! non per i noobs!
> https://forum.xda-developers.com/showpost.php?p=79626434&postcount=135

Already read many times, on YouTube I have seen some users who manage to install gltools with the temporary root seems to be true this thing only that their methods do not work, so I doubt it works

**Comment by mybillserv** [comment]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv8l machine
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


Failed critical init step 4
This platform cannot be supported
Returned 1

**Comment by Quintessential-cloud** [comment]
apparently in what I've read gltools doesn't currently support magisk v20+ maybe that's why. Probably would work on older versions just give it a try
