### ISSUE TITLE
(Resolved) Not working on LG K10 2017 (Android 8)

### ISSUE THREAD

**Issue by malidizi** [JunioJsv/mtk-easy-su#23]
Hey man, I'm very thankful for this easy root app you made. However, it turns out it doesn't work on my LG K10 2017/ LG M250N.  I installed the Magisk Manager as well. Here is the Log

Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv7l machine
param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40f6eb80
kallsyms_num_syms 48975, addr_count 48975
kallsyms_names pa 0x40f9e8d0, size 627456
kallsyms_markers pa 0x41037bd0
kallsyms_token_table pa 0x41037ed0
kallsyms_token_index pa 0x41038260
Patching credentials
Parsing current_is_single_threaded
c04a29bc: MOVW R0, #0xabe8
c04a29c0: MOVT R0, #0xc162
init_task VA: 0xc162abe8
Potential list_head tasks at offset 0x2b0
comm swapper/0 at offset 0x458
Found own task_struct at node 1
cred VA: 0xc2915400
thread_info flags VA: 0xc98d6000
seccomp mode VA: 0xe78f2830+2ac
Parsing avc_denied
c04445e4: MOVW R0, #0x5d44
c04445e8: MOVT R0, #0xc190
selinux_enforcing VA: 0xc1905d44
Setting selinux_enforcing
Switched selinux to permissive
/data/user/0/juniojsv.mtk.easy.su/files
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
source type magisk does not exist
Error in: allow magisk (null) (null) (null)
client: launching new main daemon process
Returned 0

Do you know any fix for this?

**Comment by malidizi** [comment]
New log, still not working
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv7l machine
param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40f6eb80
kallsyms_num_syms 48975, addr_count 48975
kallsyms_names pa 0x40f9e8d0, size 627456
kallsyms_markers pa 0x41037bd0
kallsyms_token_table pa 0x41037ed0
kallsyms_token_index pa 0x41038260
Patching credentials
Parsing current_is_single_threaded
c04a29bc: MOVW R0, #0xabe8
c04a29c0: MOVT R0, #0xc162
init_task VA: 0xc162abe8
Potential list_head tasks at offset 0x2b0
comm swapper/0 at offset 0x458
Found own task_struct at node 1
cred VA: 0xc7f60e80
thread_info flags VA: 0xcc854000
seccomp mode VA: 0xc6bfa1f0+2ac
Parsing avc_denied
c04445e4: MOVW R0, #0x5d44
c04445e8: MOVT R0, #0xc190
selinux_enforcing VA: 0xc1905d44
Setting selinux_enforcing
Switched selinux to permissive
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
Returned 0

**Comment by JunioJsv** [comment]
Man but for your two logs are saying that the process occurred without error, are you using magisk manager 7.1.1? I even created this app to use on my LG k10 2017 m250ds android 7.0 device and it works perfectly, I don't think you know how to use it.

**Comment by malidizi** [comment]
> Man but for your two logs are saying that the process occurred without error, are you using magisk manager 7.1.1? I even created this app to use on my LG k10 2017 m250ds android 7.0 device and it works perfectly, I don't think you know how to use it.

Yes, I have installed the latest Magisk Manager. My device is LG M250N, android version 8.1 actually.

**Comment by JunioJsv** [comment]
Just to be sure, download a terminal emulator and run the command ls -l /sbin | grep su, and send me the exit

**Comment by JunioJsv** [comment]
install version 7.1.1 of the magisk manager do not use the latest version

**Comment by JunioJsv** [comment]
> > Man but for your two logs are saying that the process occurred without error, are you using magisk manager 7.1.1? I even created this app to use on my LG k10 2017 m250ds android 7.0 device and it works perfectly, I don't think you know how to use it.
> 
> Yes, I have installed the latest Magisk Manager. My device is LG M250N, android version 8.1 actually.

the most up-to-date versions of magisk do not provide adequate support for this method to work normally, when you download the version I gave you tell me if it worked

**Comment by malidizi** [comment]
Wtf bro I swear I have been trying this for months without success, and now that I used this magisk version 7.1.1 it works. Thanks for this man

**Comment by malidizi** [comment]
![Screenshot_2020-02-06-14-58-12](https://user-images.githubusercontent.com/60132226/73943502-25664900-48f1-11ea-8ddc-6f0a197a4566.png)

**Comment by malidizi** [comment]
Btw, can I change things like system font with this root maybe?

**Comment by JunioJsv** [comment]
> Btw, can I change things like system font with this root maybe?

I am here to help :)

**Comment by malidizi** [comment]
> > Btw, can I change things like system font with this root maybe?
> 
> I am here to help :)

Just by curiosity, what things have you modified using root? I mean we have similar devices, and I would not like to get mine bricked, not even sure if changing system font can brick the device

**Comment by JunioJsv** [comment]
Just testing to know, you will close this issue.
