### ISSUE TITLE
LG K8+ N ESTA FUNCIONANDO 

### ISSUE THREAD

**Issue by andrewuka** [JunioJsv/mtk-easy-su#25]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv7l machine
param1: 0x1000, param2: 0x8040, type: 14
Building symbol table
kallsyms_addresses pa 0x40f3f820
kallsyms_num_syms 54301, addr_count 54301
kallsyms_names pa 0x40f748b0, size 697373
kallsyms_markers pa 0x4101ecd0
kallsyms_token_table pa 0x4101f030
kallsyms_token_index pa 0x4101f3c0
Patching credentials
Parsing current_is_single_threaded
c0476fd0: MOVW R12, #0xd178
c0476fd4: MOVT R12, #0xc140
init_task VA: 0xc140d178
Potential list_head tasks at offset 0x358
comm swapper/0 at offset 0x504
Found own task_struct at node 1
cred VA: 0xd554f580
thread_info flags VA: 0xc578e000
seccomp mode VA: 0xcde35358+214
Parsing avc_denied
c0405534: MOVW R12, #0x4d6c
c0405538: MOVT R12, #0xc152
selinux_enforcing VA: 0xc1524d6c
Setting selinux_enforcing
Switched selinux to permissive
Disabling seccomp
thread flags: 0x00000080
TIF_SECCOMP deactivated
seccomp mode: disabled
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
Returned 0
Acontece isso mas n faz root

**Comment by JunioJsv** [comment]
Esse dispositivo é incompatível man, por conta de ser armv7 32Bits.
