### ISSUE TITLE
Android TV layout

### ISSUE THREAD

**Issue by splitice** [JunioJsv/mtk-easy-su#26]
It would be great if this had a supported layout for TV mode. Some crappy chinese TVs can't handle portrait mode applications (display offscreen is common).

I could test on M7322 in that case.

**Comment by JunioJsv** [comment]
Try with latest version

**Comment by jerrydev010** [comment]
@splitice were you able to get su on your tv with m7322 board?

**Comment by splitice** [comment]
Nope
