### ISSUE TITLE
error mtk-su nokia 1 android pie

### ISSUE THREAD

**Issue by sachinchude** [JunioJsv/mtk-easy-su#27]
armv7l machine
param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40ab9460
kallsyms_num_syms 40556, addr_count 40556
kallsyms_names pa 0x40ae0e20, size 503776
kallsyms_markers pa 0x40b5be00
kallsyms_token_table pa 0x40b5c080
kallsyms_token_index pa 0x40b5c3d0
Patching credentials
Parsing current_is_single_threaded
Stack protection detected
c03ce590: LDR Rt, [PC, #156]  ; 0xc03ce634
init_task VA: 0xc0e2aa78
Potential list_head tasks at offset 0x290
comm swapper/0 at offset 0x438
Found own task_struct at node 1
cred VA: 0xc2635400
thread_info flags VA: 0xc3ea8000
seccomp mode VA: 0xd7517910+2ac
Parsing avc_denied
c036f634: LDR Rt, [PC, #496]  ; 0xc036f82c
selinux_enforcing VA: 0xc0ee56dc
Setting selinux_enforcing
Selinux is already permissive
Trying seccomp-forbidden syscall
Caught SIGSYS
Disabling seccomp
This address does not seem to have your thread flags (0x00000800)
seccomp mode: filter
Bad system call

**Comment by ltGuillaume** [comment]
Same for Nokia 3, whereas https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213 with init.d _does_ work.

**Comment by sachinchude** [comment]
> armv7l machine
> param1: 0x1000, param2: 0x8040, type: 12
> Building symbol table
> kallsyms_addresses pa 0x40ab9460
> kallsyms_num_syms 40556, addr_count 40556
> kallsyms_names pa 0x40ae0e20, size 503776
> kallsyms_markers pa 0x40b5be00
> kallsyms_token_table pa 0x40b5c080
> kallsyms_token_index pa 0x40b5c3d0
> Patching credentials
> Parsing current_is_single_threaded
> Stack protection detected
> c03ce590: LDR Rt, [PC, #156] ; 0xc03ce634
> init_task VA: 0xc0e2aa78
> Potential list_head tasks at offset 0x290
> comm swapper/0 at offset 0x438
> Found own task_struct at node 1
> cred VA: 0xc2635400
> thread_info flags VA: 0xc3ea8000
> seccomp mode VA: 0xd7517910+2ac
> Parsing avc_denied
> c036f634: LDR Rt, [PC, #496] ; 0xc036f82c
> selinux_enforcing VA: 0xc0ee56dc
> Setting selinux_enforcing
> Selinux is already permissive
> Trying seccomp-forbidden syscall
> Caught SIGSYS
> Disabling seccomp
> This address does not seem to have your thread flags (0x00000800)
> seccomp mode: filter
> Bad system call
