### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mohamedazzim** [JunioJsv/mtk-easy-su#28]
Not working for my Device bro...

My Device name "Lenovo Vibe K5 Note"

Help me please...

It says "Failed To Gain Root Access,Please Try Again"

Help me bro...
![Screenshot_2020-03-15-18-09-33-937](https://user-images.githubusercontent.com/57490265/76701542-25bfe400-66e8-11ea-8c38-1ae0ca5b01fe.jpeg)

**Comment by ltGuillaume** [comment]
...and this method does work? https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213/post79626434#post79626434

**Comment by JunioJsv** [comment]
send the log

**Comment by mohamedazzim** [comment]
> send

Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv8l machine
param1: 0x3000, param2: 0x18040, type: 7
Building symbol table
Can't find kallsyms addresses or offsets
Unable to get kernel symbol table
starting /system/bin/sh
UID: 10343  cap: 0000000000  selinux: enforcing  
Root user only
Returned 1

**Comment by JunioJsv** [comment]
Your device is not susceptible to the mtk su security breach, you should try another method.
