### ISSUE TITLE
Security patch (1 march 2020), Lg k11+

### ISSUE THREAD

**Issue by davidedomotica** [JunioJsv/mtk-easy-su#30]
Hi, before i got the root easily on my lg k11+ but 4 days ago i got an update with the patch of android (1 march 2020) i tried to do again the root but the application reply to me "failed to gain root, please try again". 
How can i get the root again??
Android version: 7.1.2
thanks

**Comment by JunioJsv** [comment]
You probably upgraded to the latest security patch, which was probably already aware of mtk su and inevitably ended up prohibiting this loophole in some way. Tries to go back to the previous version.
