### ISSUE TITLE
about the warning

### ISSUE THREAD

**Issue by Danilopereira82** [JunioJsv/mtk-easy-su#31]
you said 
"WARNING: DO NOT UPDATE MAGISK THROUGH MAGISK MANAGER ON A LOCKED BOOTLOADER OR YOU WILL BRICK YOUR DEVICE."

if i have the bootloader unlocked can i install magisk using the app?

**Comment by JunioJsv** [comment]
if the bootloader as unlocked your has better choices to install magisk
