### ISSUE TITLE
My Device Not Rooted

### ISSUE THREAD

**Issue by mohamedazzim** [JunioJsv/mtk-easy-su#32]
My Device Lenovo Vibe K5 Note is not getting root access...
My Device not rooted ...
Error Log...:
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv8l machine
param1: 0x3000, param2: 0x18040, type: 7
Building symbol table
Can't find kallsyms addresses or offsets
Unable to get kernel symbol table
starting /system/bin/sh
UID: 10343  cap: 0000000000  selinux: enforcing  
Root user only
Returned 1
![Screenshot_2020-03-25-10-25-25-733](https://user-images.githubusercontent.com/57490265/77503157-f72dd000-6e82-11ea-8633-bee2c4909762.jpeg)

**Comment by JunioJsv** [comment]
Your device is not susceptible to the mtk su security breach, you should try another method.

**Comment by mohamedazzim** [comment]
> Your device is not susceptible to the mtk su security breach, you should try another method.

I have tried all the methods...
Please suggest me a best way bro...
Please

**Comment by Asak-410425** [comment]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


Failed critical init step 1
exit: 1
