### ISSUE TITLE
Is it ok to upgrade Magisk?

### ISSUE THREAD

**Issue by enchantedEel** [JunioJsv/mtk-easy-su#33]
Hello Jeovane,

I was using your app to create bootless root of my ZTE A7 phone, and it returned 0 so was successful, however when I try to run Magisk manager it says I need to "upgrade to full Magisk manager to finish the setup." Is this safe to do? What do you think?

**Comment by ltGuillaume** [comment]
WARNING: DO NOT UPDATE MAGISK THROUGH MAGISK MANAGER ON A LOCKED BOOTLOADER OR YOU WILL BRICK YOUR DEVICE.

from https://github.com/JunioJsv/mtk-easy-su/blob/master/README.md

**Comment by enchantedEel** [comment]
Thank you Jeovane. But then how do I open Magisk?
I just need root access for one app that I want to use.

**Comment by ltGuillaume** [comment]
You shouldn't have to open Magisk at all. If it's installed, it will handle the root request by that app.

**Comment by enchantedEel** [comment]
The app I am trying to use, Battery Charge Limit, tells me that it is "denied root access or device is not rooted", even though I have run the Mtk-easy-su successfully

**Comment by ltGuillaume** [comment]
I had the same thing, just try this method instead of using Mtk-easy: https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213/post79626434
