### ISSUE TITLE
oppo f3 roo

### ISSUE THREAD

**Issue by umairmaher44** [JunioJsv/mtk-easy-su#36]
please make it work with oppo f3

**Comment by JunioJsv** [comment]
not every device works.

**Comment by swaily88** [comment]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv8l machine
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


Failed critical init step 1
Incompatible platform
Returned 1
oppo A3s 😢
