### ISSUE TITLE
(Resolved) Failed on Oppo A5s patch A.36

### ISSUE THREAD

**Issue by ModTackles** [JunioJsv/mtk-easy-su#37]
![Screenshot_2020-04-25-14-50-00-93](https://user-images.githubusercontent.com/63443289/80273413-69086c00-8704-11ea-9499-978840322210.jpg)

(Resolved) Failed to root my Oppo A5S with Security Patch A.36. It happen about 1 day ago..

Ps. I just try the MTK Easy SU v1.05 and it's working now..

**Comment by JunioJsv** [comment]
Was it working before?  have you tried using the previous version of mtk-easy-su?

**Comment by ModTackles** [comment]
> Was it working before? have you tried using the previous version of mtk-easy-su?

Yes it worked before but when I restart my phone it become like that.

**Comment by ModTackles** [comment]
> Was it working before? have you tried using the previous version of mtk-easy-su?

I tried your previous version, 1.0.5 and 1.0.4 but still, failed again..

**Comment by easytap** [comment]
ModTackles 
Me too!

**Comment by ModTackles** [comment]
> ModTackles
> Me too!

You are using the same Oppo A5S? Just try the MTK Easy SU v1.05. I don't know why, but its working now in that version. I already root my phone just now..

**Comment by JunioJsv** [comment]
i please try a latest version of mtk easy su, with the magisk v18.1 asset and tell me if it worked

**Comment by Samra0072** [comment]
> ![Screenshot_2020-04-25-14-50-00-93](https://user-images.githubusercontent.com/63443289/80273413-69086c00-8704-11ea-9499-978840322210.jpg)
> 
> (Resolved) Failed to root my Oppo A5S with Security Patch A.36. It happen about 1 day ago..
> 
> Ps. I just try the MTK Easy SU v1.05 and it's working now..

I want new version mtk

**Comment by easytap** [comment]
Yup it's work on two day ago i'm restart my phone and it's work !
👍👍👍👍


Vào 11:55, Th 2, 27 thg 4, 2020 Samra0072 <notifications@github.com> đã
viết:

**Comment by Samra0072** [comment]
Oh! By version v1.05 its working and with asset v18
Thanks sir

**Comment by ModTackles** [comment]
> Hi, please try a latest version of mtk easy su, with the magisk v18.1 asset and tell me if it worked

![Screenshot_2020-04-28-14-26-49-42](https://user-images.githubusercontent.com/63443289/80454295-686a1280-895c-11ea-9b13-a642833ca5d6.jpg)
Yes it works.  Thank you.. 😇
