### ISSUE TITLE
Code file faild

### ISSUE THREAD

**Issue by easytap** [JunioJsv/mtk-easy-su#39]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

/data/data/juniojsv.mtk.easy.su/files
UID: 0  cap: 3fffffffff  selinux: permissive  
Load policy from: /sys/fs/selinux/policy
Bad system call 
Bad /sbin mount?
Exit value 1

**Comment by JunioJsv** [comment]
Hello man, try again with latest version
