### ISSUE TITLE
(Resolved) Lenovo Tab 4 Successfully Roots, Magisk Manager doesn't see magisk running.

### ISSUE THREAD

**Issue by jericotyler** [JunioJsv/mtk-easy-su#40]
Factory reset the device, sideloaded mtk-easy-su and Magisk Manager 7.1.1, both installed and easy-su says it's gotten root. M.M. doesn't show that magisk is "installed" and root checker doesn't see it as rooted either.
![Screenshot_2020-04-24-03-10-23-430](https://user-images.githubusercontent.com/22330993/80187464-ade5b300-85dd-11ea-8d31-450fa6890365.jpeg)
![Screenshot_2020-04-24-03-18-05-853](https://user-images.githubusercontent.com/22330993/80187466-ae7e4980-85dd-11ea-975a-06429f51b3e0.jpeg)
![Screenshot_2020-04-24-03-35-55-865](https://user-images.githubusercontent.com/22330993/80187467-ae7e4980-85dd-11ea-9ff0-97f8fed6c638.jpeg)

**Comment by jericotyler** [comment]
Processor is an MT8163 and it's the 1GB version of the Lenovo Tab4 8"

**Comment by JunioJsv** [comment]
Try another version of Magisk Manager

**Comment by jericotyler** [comment]
Tried versions 5.04 up to the latest (7.5.1) and none of them seemed to see magisk running. Seeing as how most of the older versions just crash I don't know if trying to go older than that is a worthwhile endeavor.

**Comment by JunioJsv** [comment]
Hi dude, try again on latest verdion with magisk v18.1 asset

**Comment by jericotyler** [comment]
- Uninstalled Magisk Manager and Mtk-Easy-Su
- Installed the new version of Easy-su and MM 7.1.1
- Clicked install on v18.1 in the app, rebooted when it asked me to
- Opened the app again and clicked activate, it asked me to reboot.
- After the second reboot it ran and gave me this log after flashing "success" followed by "can't access file"

> param1: 0x3000, param2: 0x18040, type: 2
> Building symbol table
> kallsyms_addresses pa 0x40b32e00
> kallsyms_num_syms 51340, addr_count 51340
> kallsyms_names pa 0x40b97400, size 630756
> kallsyms_markers pa 0x40c31400
> kallsyms_token_table pa 0x40c31b00
> kallsyms_token_index pa 0x40c31f00
> Patching credentials
> Parsing current_is_single_threaded
> ffffffc0003433e4+50: ADRP x0, 0xffffffc000e1a000
> ffffffc0003433e4+54: ADD xd, x0, 2576
> init_task VA: 0xffffffc000e1aa10
> Potential list_head tasks at offset 0x340
> comm swapper/0 at offset 0x5c8
> Found own task_struct at node 1
> cred VA: 0xffffffc00c6cbe80
> Parsing avc_denied
> ffffffc0002e3208+24: ADRP x0, 0xffffffc000f45000
> ffffffc0002e3208+28: LDR [x0, 3948]
> selinux_enforcing VA: 0xffffffc000f45f6c
> Setting selinux_enforcing
> Switched selinux to permissive
> /mnt/expand/dd54e66f-957b-4534-956c-8235ce5c3d11/user/0/juniojsv.mtk.easy.su/files
> armv8l machine
> starting /system/bin/sh
> UID: 0  cap: 3fffffffff  selinux: permissive  
> source type magisk does not exist
> Error in: allow magisk (null) (null) (null)
> client: launching new main daemon process
> exit value 0 assets-r20

**Comment by jericotyler** [comment]
Decided to poke around in the shell:

> TB-8304F1:/ $ ps | grep magisk
> 1|TB-8304F1:/ $ ps | grep magisk
> root      3902  1     20016  1744  __skb_recv 0000000000 S magiskd
> root      3921  1     20664  948   __skb_recv 0000000000 S magisklogd
> root      3954  3921  16212  1664  __skb_recv 0000000000 S /sbin/.magisk/mirror/system/bin/logcat
> TB-8304F1:/ $ su
> Permission denied

Seems to actually start magisk, yet the manager still doesn't like it.

**Comment by JunioJsv** [comment]
https://github.com/JunioJsv/mtk-easy-su/blob/d84b2c799b8155778ed53a44237cc59a6c090158/app/src/main/java/juniojsv/mtk/easy/su/AssetsManager.kt#L99-L103

I'm almost sure that the error is in this line of code, this line erases the residues of the magisk so that a new daemon is started normally, but without a device it doesn't seem to have this folder /data/ like most, do you have any suggestions?

**Comment by JunioJsv** [comment]
you have to find this folder on your device and delete these files
![Screenshot_2020-04-27-23-54-42](https://user-images.githubusercontent.com/39963398/80442144-bd694280-88e2-11ea-8e71-d6d9e43e2605.png)

**Comment by JunioJsv** [comment]
I think it's in the folder /mnt/expand/dd54e66f-957b-4534-956c-8235ce5c3d11/adb

**Comment by jericotyler** [comment]
It was in the root level directory as /data/adb deleted the folder, rebooted, and ran easy-su.
Got the same log output and results as before.

**Comment by jericotyler** [comment]
Soooooooo... I just learned if you have an SD card android installs new apps there by default.
After moving both magisk and easy root to the internal storage everything works!

**Comment by jericotyler** [comment]
I apologize for the run around, It's been 5 years since I've used android extensively and I forgot I should check for that. Would it be possible to add something to check that both Magisk Manager and MTK-Easy-Su are installed in internal storage? Just to solve any future headaches?

**Comment by JunioJsv** [comment]
Nice!

**Comment by 3ndlessly** [comment]
> Factory reset the device, sideloaded mtk-easy-su and Magisk Manager 7.1.1, both installed and easy-su says it's gotten root. M.M. doesn't show that magisk is "installed" and root checker doesn't see it as rooted either.
> ![Screenshot_2020-04-24-03-10-23-430](https://user-images.githubusercontent.com/22330993/80187464-ade5b300-85dd-11ea-8d31-450fa6890365.jpeg)
> ![Screenshot_2020-04-24-03-18-05-853](https://user-images.githubusercontent.com/22330993/80187466-ae7e4980-85dd-11ea-975a-06429f51b3e0.jpeg)
> ![Screenshot_2020-04-24-03-35-55-865](https://user-images.githubusercontent.com/22330993/80187467-ae7e4980-85dd-11ea-9ff0-97f8fed6c638.jpeg)

Open " magisk root granter" and granter in manually

**Comment by siddhpant** [comment]
Which magisk version works now? I'm trying to do this on an Android 7, but latest magisk seems to have the superuder option greyed out
