### ISSUE TITLE
Can't root Huawei Y5 2019

### ISSUE THREAD

**Issue by bbaranoff** [JunioJsv/mtk-easy-su#42]
Hello root fail on Huawei Y5 2019
Got this 

param1: 0x1000, param2: 0x8040, type: 14
Building symbol table
armv8l machine
Can't find kallsyms addresses or offsets
Unable to get kernel symbol table
setns failed: No such file or directory
Bad system call 
exit value 159 assets-r20

**Comment by saretto282000** [comment]
> Ciao root fallito su Huawei Y5 2019
> Capito
> 
> param1: 0x1000, param2: 0x8040, tipo: 14
> Creazione della tabella dei
> simboli macchina armv8l
> Impossibile trovare gli indirizzi o gli offset di kallsyms
> Impossibile ottenere la tabella dei simboli del kernel
> setns non riuscita: nessun file o directory
> non
> valido Valore di uscita chiamata di sistema 159 assets-r20

have you tried with the previous version to me it no longer makes me root after installing the latest version

**Comment by bbaranoff** [comment]
Trying to find r19... But no luck :(

**Comment by saretto282000** [comment]
> Cercando di trovare r19 ... Ma senza fortuna :(

:/

**Comment by bbaranoff** [comment]
found r19 and r18 but no more luck
https://github.com/pikpikcu/mtk-su/

**Comment by bbaranoff** [comment]
HWAMN-M:/data/local/tmp/mtk-su $ LD_PRELOAD=./syscall_hook.so ./mtk-su         
alloc failed
alloc count=400 startPA=0x87585000
uncatched ioctl 40e07803
FORTIFY: fwrite: null FILE*

Instead of 

$ mkdir mtk-su
$ LD_PRELOAD=./syscall_hook.so ./mtk-su
alloc failed
alloc count=400 startPA=0x53df4000
uncatched ioctl 40e07803
exec command (num 0) ( blockSize=8040, readAddress.count=0 ) dumped into cmd-0
exec command (num 1) ( blockSize=3e0, readAddress.count=1e ) dumped into cmd-1
exec command (num 2) ( blockSize=3e0, readAddress.count=1e ) dumped into cmd-2
[...]
$ cat  mtksu/cmd-1
WFE to_wait=1, wait=1, to_update=1, update=0, event=1da
MOVE 40a68000 into reg 17
READ  address reg 17, data reg b
MOVE startPA+0 into reg 17
WRITE  address reg 17, data reg b
[...]

May this usefull...
