### ISSUE TITLE
Failed root

### ISSUE THREAD

**Issue by saretto282000** [JunioJsv/mtk-easy-su#43]
installing the latest version of mediatek Easy root on nougat no longer makes temporary root even with the previous version please solve this problem.

ok i solved

**Comment by saretto282000** [comment]
> installing the latest version of mediatek Easy root on nougat no longer makes temporary root even with the previous version please solve this problem.
![Screenshot_20200427-164144](https://user-images.githubusercontent.com/64422395/80385360-3f874600-88a6-11ea-8ea4-2e93517d564a.png)
![Screenshot_20200427-164151](https://user-images.githubusercontent.com/64422395/80385426-55950680-88a6-11ea-9134-d5f9846a230b.png)
i rebooted many times but nothing

**Comment by yfox98** [comment]
I'm having the same problem, after i update from 1.0.5 to 1.1.0 now the app return this:
(My device is an LG-M320TV with the European 8.1.0 rom)
`param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40f335a0
kallsyms_num_syms 49271, addr_count 49271
kallsyms_names pa 0x40f63790, size 631393
kallsyms_markers pa 0x40ffda00
kallsyms_token_table pa 0x40ffdd10
kallsyms_token_index pa 0x40ffe090
Patching credentials
Parsing current_is_single_threaded
Parsing avc_denied
c045932c: MOVW R0, #0x7604
c0459330: MOVT R0, #0xc190
selinux_enforcing VA: 0xc1907604
Setting selinux_enforcing
Selinux is already permissive
armv7l machine
Stack protection detected
init_task not found
setns failed: No such file or directory
starting /system/bin/sh
UID: 12290  cap: 0000000000  selinux: permissive  
Root user only
exit value 1 assets-r20`

**Comment by saretto282000** [comment]
> Sto riscontrando lo stesso problema, dopo l'aggiornamento da 1.0.5 a 1.1.0 ora l'app restituisce questo:
> (Il mio dispositivo è un LG-M320TV con la rom europea 8.1.0)
> `param1: 0x1000, param2: 0x8040, type: 12 Building symbol table kallsyms_addresses pa 0x40f335a0 kallsyms_num_syms 49271, addr_count 49271 kallsyms_names pa 0x40f63790, size 631393 kallsyms_markers pa 0x40ffda00 kallsyms_token_table pa 0x40ffdd10 kallsyms_token_index pa 0x40ffe090 Patching credentials Parsing current_is_single_threaded Parsing avc_denied c045932c: MOVW R0, #0x7604 c0459330: MOVT R0, #0xc190 selinux_enforcing VA: 0xc1907604 Setting selinux_enforcing Selinux is already permissive armv7l machine Stack protection detected init_task not found setns failed: No such file or directory starting /system/bin/sh UID: 12290 cap: 0000000000 selinux: permissive Root user only exit value 1 assets-r20`

Ciao prova a reinstallare magisk e poi installa l'ultima versione di mediatek Easy root dovrebbe risolvere il problema

**Comment by yfox98** [comment]
I tried but, it failed
`Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv7l machine
param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40f335a0
kallsyms_num_syms 49271, addr_count 49271
kallsyms_names pa 0x40f63790, size 631393
kallsyms_markers pa 0x40ffda00
kallsyms_token_table pa 0x40ffdd10
kallsyms_token_index pa 0x40ffe090
Patching credentials
Parsing current_is_single_threaded
c04ba114: MOVW R0, #0xaab0
c04ba118: MOVT R0, #0xc162
init_task VA: 0xc162aab0
Potential list_head tasks at offset 0x2b0
comm swapper/0 at offset 0x458
Found own task_struct at node 1
cred VA: 0xe85e6500
thread_info flags VA: 0xe9126000
seccomp mode VA: 0xc9bdf130+2ac
Parsing avc_denied
c045932c: MOVW R0, #0x7604
c0459330: MOVT R0, #0xc190
selinux_enforcing VA: 0xc1907604
Setting selinux_enforcing
Switched selinux to permissive
Stack protection detected
Retrying...
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
Load policy from: /sys/fs/selinux/policy
exit value 0 assets-r21`

**Comment by yfox98** [comment]
It looks like that I will have to stay with 1.0.5 '-'
