### ISSUE TITLE
MTK easy su failed to activate bootless root please install a asset

### ISSUE THREAD

**Issue by Gamemulatorer** [JunioJsv/mtk-easy-su#47]
Clicking "activate bootless root" always show please install a asset this only happen in v1.1.1
![Screenshot_20200508-104738](https://user-images.githubusercontent.com/37603562/81365960-28551d80-911c-11ea-93ff-43462e1a8aff.png)

Can't grant root access anymore because of this issue :(

**Comment by JunioJsv** [comment]
connect the internet, install an asset, restart the device, click activate root and be happy.

**Comment by Gamemulatorer** [comment]
How can install a asset there's no guide about :P

**Comment by JunioJsv** [comment]
Putz cara, vc é br ne, você tem que abrir o app com a internet ligada, dai no card de preferências dentro do app msm, você aperta no botão que tem o nome install.

**Comment by JunioJsv** [comment]
![Capture+_2020-05-08-00-47-37](https://user-images.githubusercontent.com/39963398/81368238-a33f1980-90c5-11ea-80cc-04b2fd5010fd.png)

**Comment by Gamemulatorer** [comment]
Unfortunately magisk zip is not showing under asset on my phone with android 6.0 mt6580 cpu
![Screenshot_20200508-120435](https://user-images.githubusercontent.com/37603562/81369661-8fc39b00-9125-11ea-944f-c53309a4dd03.png)
![Screenshot_20200508-120442](https://user-images.githubusercontent.com/37603562/81369678-994d0300-9125-11ea-8e0a-506738e9e7c8.png)

**Comment by Gamemulatorer** [comment]
OK After minutes the magisk zip install is finally showing, but after downloading and installing the zip mtk easy su app is crashing.
![Screenshot_20200508-140343](https://user-images.githubusercontent.com/37603562/81376888-fa310700-9136-11ea-8acc-dfdf8cfb86ef.png)

Also after reboot this is what is showing in logs
![Screenshot_20200508-140603](https://user-images.githubusercontent.com/37603562/81376949-116ff480-9137-11ea-8a43-cda99f7539ca.png)

maybe you need to add storage permission?

**Comment by JunioJsv** [comment]
I took this permission thinking that it would not be necessary, but I will put it back this afternoon. on my device is working normally.

**Comment by Gamemulatorer** [comment]
Even after installating the assets, app still asking for this "please install a asset"
![Screenshot_20200508-230219](https://user-images.githubusercontent.com/37603562/81419137-5cfac080-9180-11ea-9f61-e17ac8c10e95.png)

**Comment by JunioJsv** [comment]
hey dude try with this version https://github.com/JunioJsv/mtk-easy-su/releases/tag/v1.1.2

**Comment by Gamemulatorer** [comment]
Confirmed issue was solved 🎉
![FJIMG_20200509_020223](https://user-images.githubusercontent.com/37603562/81435034-be7b5900-9199-11ea-971f-9f4d635cc416.jpg)

**Comment by Drogo-debug** [comment]
My redmi6a showing failed try again

**Comment by RavmAgA** [comment]
How about this problem. Oppo A5s
![Screenshot_2020-12-12-15-43-29-86](https://user-images.githubusercontent.com/75877768/101978654-7ffacf00-3c91-11eb-991f-c540bc67658d.jpg)

**Comment by Mr-Mental** [comment]
![Screenshot_2021-05-06-12-48-52](https://user-images.githubusercontent.com/69758640/117257657-c41d8480-ae69-11eb-8fcb-120256088b96.png)
what shall i dp now

**Comment by Mr-Mental** [comment]
![Screenshot_2021-05-06-12-48-52](https://user-images.githubusercontent.com/69758640/117257768-df888f80-ae69-11eb-818b-1e958b17906f.png)
my phone is lg k10
what should i do now
help me pls

**Comment by Sgr7777** [comment]
![Screenshot_20220208-133220_Chrome](https://user-images.githubusercontent.com/99238160/152924649-03b36c4a-a646-4fc9-8281-dc5f1d68a66d.jpg)
I restarted several times but it didn't work

**Comment by Sgr7777** [comment]
![Screenshot_20220208-133105_Mtk Easy Su](https://user-images.githubusercontent.com/99238160/152924722-5a0ed97e-39b3-4810-8494-cb7b960336ce.jpg)
I rebootI restarted several times but it didn't work

**Comment by Sgr7777** [comment]
![Screenshot_20220208-141628_Mtk Easy Su](https://user-images.githubusercontent.com/99238160/152929476-d905a80e-5469-4bfa-b4f6-501adb62bfd9.jpg)
How to solve

**Comment by mostafa513660** [comment]
![Screenshot_20230105-012024](https://user-images.githubusercontent.com/83466461/210668350-6c1592fd-ed1c-488e-aaa5-67123059739d.jpg)


pleas help me
the app said "fail try again"
my phone is : Infinix Smart 5
The Model is : X657B
My android is : 11

**Comment by Belu-momhn** [comment]
`su` is has connect 
```
/data/user/0/juniojsv.mediatekeasyroot/files/suboot.sh[96]: ./magiskinit: Permission denied
Returned 1
^^^^^^^^^^^^^^^
``` 
SuperSu + magisk 

- [ ] has not found
- [ ] magisk is has setup no loger

**Comment by YaguinhoZxz** [comment]
> feliz

Can you help me, I did TD correctly, I installed it and restarted the phone, and when I go to press to root it says "please reboot in Device" even after having already restarted

**Comment by Ronal-6** [comment]
![Screenshot_20250106_153433](https://github.com/user-attachments/assets/93b5b772-e3c1-4f0a-9fcc-7ffd8586d92d)

Please solution

**Comment by Ronal-6** [comment]
![Screenshot_20250106_153433](https://github.com/user-attachments/assets/ca38d0e8-f924-4960-b20b-62765c76e446)

My phone vivo 1820
Version : Oreo 8.1

**Comment by MikeVikulov26** [comment]
It doesn't work for me on version 1.1.2. I downloaded the magizk and rebooted the tablet and went in and pressed "get unbootable root" and it says "error"

![Image](https://github.com/user-attachments/assets/318ac16f-771f-4c7d-9fec-2a1d72f37419)

**Comment by MikeVikulov26** [comment]
I have a tablet Huawei BTV-DL09 Android 6.0
