### ISSUE TITLE
Please reboot your device (Redmi 6A)

### ISSUE THREAD

**Issue by nabieladrian** [JunioJsv/mtk-easy-su#48]
Have been looping around with these assets, have been rebooted too.
Also, no log.

![Screenshot_2020-05-09-04-59-48-976_juniojsv mtk easy su](https://user-images.githubusercontent.com/64706096/81453471-cd6f0500-91b3-11ea-9c41-768be74de631.jpg)

**Comment by nabieladrian** [comment]
**UPDATE** ROOT SUCCESS(?)

I kept the Mtk Easy Su running in the background, phone got laggy by several minutes then some toast notifications popped up
(i haven't take screenshot or even remembered what it says, since its so sudden).

I just quickly go back to the app and it says "success" (still no log, fyi).
Here's the check:

![Screenshot_2020-05-09-05-23-13-421_juniojsv mtk easy su](https://user-images.githubusercontent.com/64706096/81454836-8a169580-91b7-11ea-8339-e99a5f48b866.jpg)

![Screenshot_2020-05-09-05-24-58-101_com joeykrim rootcheck](https://user-images.githubusercontent.com/64706096/81454795-7408d500-91b7-11ea-905a-4ad675795c8d.jpg)

Thanks for the work! It ain't much but it honest works.

**Comment by Drogo-debug** [comment]
My redmi6a not working

**Comment by Drogo-debug** [comment]
Any problem with bootloader unlocked

**Comment by JunioJsv** [comment]
Send the log dude.

**Comment by Drogo-debug** [comment]
Showing like this with no log
