### ISSUE TITLE
Failed try again

### ISSUE THREAD

**Issue by Drogo-debug** [JunioJsv/mtk-easy-su#50]
After installing assets showing pls reboot your device then showing 'failed try again'

**Comment by JunioJsv** [comment]
Stop span the same issue dude!

**Comment by JunioJsv** [comment]
Send the log, without this i can't help.

**Comment by yassen-650** [comment]
![Uploading IMG_٢٠٢١٠١١٤_٠٠٤٦٣٧.jpg…]()

**Comment by yassen-650** [comment]
![Uploading IMG_٢٠٢١٠١١٤_٠٠٤٦٣٧.jpg…]()
