### ISSUE TITLE
Error, Nokia 3.1

### ISSUE THREAD

**Issue by nicknickeryt** [JunioJsv/mtk-easy-su#51]
I tried to aquire root on my phone, but after installing it showed up a notification about that a reboot is required. Hovewer, nothing happens after a reboot. One time, it showed up a notification and said that the root failed, next time there wasn't any notification. Magisk 20.4 is showed up as installed, but it isn't.
![Screenshot_20200510-222630](https://user-images.githubusercontent.com/37023408/81509984-ed670b80-930e-11ea-8510-e37665d76e43.png)
There is no log.

**Comment by Monkeyboy2805** [comment]
Same situation on Nokia 2.2
