### ISSUE TITLE
Novo Mediatek, LG K11+ ( Patch de segurança, 1 março de 2020 )

### ISSUE THREAD

**Issue by hmattoss** [JunioJsv/mtk-easy-su#53]
Opa, com o novo patch de segurança da lg o mediatek easy root não consegue a raiz temporária como você deve saber, num futuro, você conseguiria criar um "novo" Mediatek easy root que não fosse "detectado" por esse patch de segurança da lg?

**Comment by PedroGuilherme17** [comment]
I'm having the same problem with a TCL L9

**Comment by JunioJsv** [comment]
Acho que a única solução por enquanto é fazer um downgrade '-'

**Comment by andreacc** [comment]
Estou com o mesmo problema. Comprei um LG K40S, atualizei e não consigo rootear de jeito nenhum. Também não consigo fazer downgrade, nem por meio de restauração de fábrica nem por meio do LG Flash Tool, que dá erro.
