### ISSUE TITLE
Root failed

### ISSUE THREAD

**Issue by vatsalgajjar** [JunioJsv/mtk-easy-su#58]
Log is here

Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv8l machine
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

Failed critical init step 1
Incompatible platform
exit value 1 assets-r22

**Comment by PedroGuilherme17** [comment]
I have the same problem, I believe it will take a long time to fix it
