### ISSUE TITLE
Sir my oppo f11 plz do something its not root

### ISSUE THREAD

**Issue by Ajaz0** [JunioJsv/mtk-easy-su#63]
armv8l machine
Failed critical init step 4
Firmware support not implemented
returned 1
And not doing something

**Comment by tono122** [comment]
Restart you mobile and Connect two Oppo f11 phone on hot-spot Wi-Fi and
root it worked

**Comment by Ajaz0** [comment]
Sir try all but there is nothing do anything process can u plz send me a video if you do plz help us my  gmail muhammadajaz7786@gmail.com or no 8839786266 what's app me plz video

**Comment by Ajaz0** [comment]
Plz help sir

**Comment by Ajaz0** [comment]
Are you seen me try if you can do
![Screenshot_2020-07-19-22-48-43-05_483d806fe14069299732760b15eae342](https://user-images.githubusercontent.com/68477584/87880781-1e03a980-ca12-11ea-8253-85d1d0032a29.jpg)

**Comment by Rob801130** [comment]
Mtk easy su
