### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by Lucas559-noob** [JunioJsv/mtk-easy-su#68]
I'm on lg k40s and I see that i need to download an asset, but i think if I download and restart, it will brick my phone because I don't have bootloader or other thing
I rooted my other phone(lg k10) but it is dead... but It wasn't needed to download assets, after a time it started to stop working
so there is a way to make it work without the assets? and I automatic installed the last update on phone so is impossible?

**Comment by JunioJsv** [comment]
hello, I don't intend to update this project anymore. if you do not know very well what you are doing it is better not to try.
