### ISSUE TITLE
Vivo y91c not work

### ISSUE THREAD

**Issue by lasarus23** [JunioJsv/mtk-easy-su#70]
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

armv8l machine
Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------

Failed critical init step 4
This firmware cannot be supported
exit value 1 assets-r23

**Comment by qwcfc** [comment]
Mtk su vivo v9 1723 please
