### ISSUE TITLE
Works on Alcatel 1 (Telstra Essential Plus 5033T) , but does not work on Alcatel 4047A MT6580M

### ISSUE THREAD

**Issue by skygunner** [JunioJsv/mtk-easy-su#8]
Works on Alcatel 1 (Telstra Essential Plus 5033T)  MT6739 Android Oreo Go, 
but does not work on 4047A (Telstra Alcatel U5 3G) MT6580M Android 7.0

**Comment by skygunner** [comment]
I guess this use the mtk-su, which only works for MediaTek ARMv8 64bit like
MT67xx, MT816x, and MT817x!

**Comment by JunioJsv** [comment]
good observation. thanks for the feedback

**Comment by JunioJsv** [comment]
Pls, try again with v1.0.4, and send the log here.
