### ISSUE TITLE
Oppo a5s root failed try again after new update CPH1909EX_11_A.41

### ISSUE THREAD

**Issue by BABBUGURM** [JunioJsv/mtk-easy-su#80]
How to fix it bro

**Comment by dreyliba** [comment]
pls find how to fix it

**Comment by lucchieu** [comment]
Same :  CPH1912EX_11A.41

**Comment by Nath261203** [comment]
Same

**Comment by tenar0** [comment]
Please solve the problem and release the new version of your programs. Thank you very much, the developers, for this work

**Comment by JunioJsv** [comment]
Acho que eu não posso fazer nada, não tenho esse dispositivo e muito menos o código fonte do mtk-su do Diplomatic.

**Comment by Nath261203** [comment]
Apakah bisa membuat aplikasi mtk eazy root support dengan oppo versi sekarang?

**Comment by vijay755vijay** [comment]
I have oppo a5s and I try to root it shows failed to get root access,so please check the issue and help me

**Comment by JunioJsv** [comment]
Hey, try this #92

**Comment by gsmeockybhai** [comment]
oppo.a5s root failed pzzz solved

**Comment by zezo-089** [comment]
guys
oppo a5s root is here !
https://forum.xda-developers.com/t/guide-root-unlock-bootloader-for-oppo-a5s-cph1909-after-security-update-without-downgrading-the-version-of-the-phone.4587745/
