### ISSUE TITLE
Oppo a5s

### ISSUE THREAD

**Issue by NighttMare26** [JunioJsv/mtk-easy-su#81]
I install a asset mtk easy su and my phone is oppo a5s after I install a asset I reboot my phone and after it I open mtk easy su and tap activate bootless root and failed to gain root access

**Comment by jhayke1226** [comment]
Try rebooting again
Like double reboot

**Comment by JunioJsv** [comment]
Try this ![]#92

**Comment by zezo-089** [comment]
https://forum.xda-developers.com/t/guide-root-unlock-bootloader-for-oppo-a5s-cph1909-after-security-update-without-downgrading-the-version-of-the-phone.4587745/
