### ISSUE TITLE
Oppo A5S Root failed after updated new version

### ISSUE THREAD

**Issue by Gamer2r** [JunioJsv/mtk-easy-su#83]
I'm getting root failed message after updated oppo A5s so please fix issue 
Please find the attached log details
![Screenshot_2020-10-19-01-21-00-31](https://user-images.githubusercontent.com/73079143/96378559-5e59fb80-11aa-11eb-8e80-d36e0e4abe09.jpg)
![Screenshot_2020-10-19-01-21-11-38](https://user-images.githubusercontent.com/73079143/96378567-77fb4300-11aa-11eb-8968-79e7f938aaf5.jpg)

**Comment by jhayke1226** [comment]
What version of magisk and mtk easy su you use?
Im also in oppo a5s and using both updated

**Comment by Gamer2r** [comment]
Magistck 7.1.1 and easy Su .I was working before but the no root access
after updated my phone

**Comment by Gamer2r** [comment]
https://github.com/JunioJsv/mtk-easy-su/releases/tag/v1.0.5-final
This version was working awesome but not working

**Comment by Gamer2r** [comment]
Dear sir,
Please find the attached version of super su v1.0.5 with log details. It
was working perfectly in my previous Oppo version but it's not working
after update the Oppo phone version.

I would like to say that your app is really priceless to me .

Thanks for your response and I hope you will solve the issue and you will
update the app for new versions mobiles .

**Comment by Gamer2r** [comment]
![Uploading Screenshot_2020-11-08-06-49-24-54.jpg…]()

**Comment by JunioJsv** [comment]
Eai, não posso fazer nada sobre isso, não tenho o código fonte do mtk-su, não tenho um dispositivo do mesmo modelo que o seu e agora nem tenho mais computador! Se vira aí.

**Comment by JunioJsv** [comment]
Se quiser tentar, você pode fazer um downgrade em seu dispositivo.

**Comment by Gamer2r** [comment]
Fiz downgrade do meu celular e uso Mtk easy Su v1.0.5, mas não consigo
manter a versão antiga.  Deixe-me saber qual telefone é adequado para Mtk
Su, porque eu posso, mas um novo telefone para seu aplicativo.  Espero que
você possa atualizar Mtk Su para todas as versões móveis porque você é um
gênio genuíno

**Comment by JunioJsv** [comment]
Se vc esta disposto a comprar um novo dispositivo, não seria melhor compra um que tenha custom roms e fácil acesso a super usuário?! Eu uso um lg k10 2017 e o app funciona normalmente.

**Comment by Gamer2r** [comment]
markS funcionará com nova versão desse celular também?  deixe-me saber qual
é a versão do seu dispositivo

**Comment by JunioJsv** [comment]
Android 8.1 path de segurança de 2018.

**Comment by Gamer2r** [comment]
pergunta final, você está usando a versão mais recente do LG K10 2017
porque eu só queria confirmar se eu enfrento o mesmo problema depois de
atualizar o LG K10 2017 para celular

**Comment by JunioJsv** [comment]
Não faço ideia se essa é a última versão.

**Comment by Gamer2r** [comment]
muito obrigado pela sua ótima resposta.  Vou tentar comprar um novo
telefone LGk10 hoje, mas tenho um humilde requisito de atualizar o mtk Su
para trabalhar com o projeto mais recente também, porque dependemos do seu
aplicativo de desenvolvedor mtk Su.  seu aplicativo é melhor do que todos
os aplicativos raiz e você está fazendo um ótimo trabalho.  obrigado senhor
e obrigado novamente
