### ISSUE TITLE
read only filesystem

### ISSUE THREAD

**Issue by Sergei-Alekseev** [JunioJsv/mtk-easy-su#90]
[mtkeasysulog.txt](https://github.com/JunioJsv/mtk-easy-su/files/5646425/mtkeasysulog.txt)
LG Q7 android 8.1
Badly need root access to change some system prefs and remove bloatware.
No other install root options for that device. Pls help if you can.
Thanks.

**Comment by Sergei-Alekseev** [comment]
Still the same in latest version.

**Comment by JunioJsv** [comment]
type these commands in sequence in your terminal, to mount the /system as rw

```sh
su -c killall system_server #hot restart, to bypass the verification that prevents remount the /system
su -c mount -o rw,remount /system #mount /system as read write
```

**Comment by Sergei-Alekseev** [comment]
What? "su -c"? Its impossible because no root on the phone.

**Comment by Sergei-Alekseev** [comment]
The same in 2.0.2


Temporary root by diplomatic@XDA
Home URL:
https://forum.xda-developers.com/android/development/amazing-temp-root-mediatek-armv8-t3922213
--------------------------------------------------


armv7l machine
param1: 0x1000, param2: 0x8040, type: 12
Building symbol table
kallsyms_addresses pa 0x40e9e120
kallsyms_num_syms 49977, addr_count 49977
kallsyms_names pa 0x40ecee20, size 639226
kallsyms_markers pa 0x40f6af20
kallsyms_token_table pa 0x40f6b230
kallsyms_token_index pa 0x40f6b5c0
Patching credentials
Parsing current_is_single_threaded
c04bd3d4: MOVW R4, #0x2648
c04bd3dc: MOVT R4, #0xc142
Possible list_head tasks at offset 0x2b0
comm swapper/0 at offset 0x458
Found own task_struct at node 1
cred VA: 0xdbdee300
thread_info flags VA: 0xc3bd4000
seccomp mode VA: 0xdfc04a30+2ac
init_task VA: 0xc142abb0
Parsing avc_denied
c045ab84: MOVW R0, #0x7d44
c045ab88: MOVT R0, #0xc170
selinux_enforcing VA: 0xc1707d44
Setting selinux_enforcing
Switched selinux to permissive
Disabling seccomp
thread flags: 0x00000800
TIF_SECCOMP deactivated
seccomp mode: disabled
starting /system/bin/sh
UID: 0  cap: 3fffffffff  selinux: permissive  
'/dev/root' is read-only
chmod: chmod '/root' to 40750: Read-only file system
ln: cannot create hard link from '/sbin/bnrd' to '/root/bnrd': Read-only file system
ln: cannot create hard link from '/sbin/charger' to '/root/charger': Read-only file system
ln: cannot create hard link from '/sbin/fuelgauged_static' to '/root/fuelgauged_static': Read-only file system
ln: cannot create hard link from '/sbin/rctd' to '/root/rctd': Read-only file system
ln: cannot create hard link from '/sbin/ueventd' to '/root/ueventd': Read-only file system
ln: cannot create hard link from '/sbin/watchdogd' to '/root/watchdogd': Read-only file system
Error making /sbin hardlinks
exit: 1

**Comment by Sergei-Alekseev** [comment]
ok. what to do now?

127|mcv5a:/data/local/tmp # ./su -c killall system_server
./su -c killall system_server
mcv5a:/data/local/tmp #
c:\ADB_Fastboot>adb shell
mcv5a:/ $ getenforce
getenforce
Permissive
mcv5a:/ $ cd /data/local/tmp
cd /data/local/tmp
mcv5a:/data/local/tmp $ ./su -c mount -o rw,remount /system
./su -c mount -o rw,remount /system
mount: '/system' not in /proc/mounts
1|mcv5a:/data/local/tmp $ ./su -c cat /proc/mounts
./su -c cat /proc/mounts
rootfs / rootfs rw,seclabel 0 0
/dev/root / ext4 ro,seclabel,relatime,data=ordered 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=1428136k,nr_inodes=159879,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
/dev/block/dm-1 /vendor ext4 ro,seclabel,relatime,data=ordered 0 0
none /acct cgroup rw,relatime,cpuacct 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,relatime,size=1428136k,nr_inodes=159879,mode=755,gid=1000 0 0
none /config configfs rw,relatime 0 0
none /dev/cpuctl cgroup rw,relatime,cpu 0 0
pstore /sys/fs/pstore pstore rw,seclabel,relatime 0 0
/dev/pstore /dev/pstore pstore rw,seclabel,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/protect1 /vendor/protect_f ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/protect2 /vendor/protect_s ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/nvdata /vendor/nvdata ext4 rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/nvcfg /vendor/nvcfg ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/persist /vendor/persist ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/power /vendor/power ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/els /vendor/els ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/persist_lg /vendor/persist-lg ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/mpt /vendor/mpt ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/carrier /vendor/carrier ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/oem_a /oem ext4 ro,context=u:object_r:op_file:s0,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/OP_a /oem/OP ext4 ro,context=u:object_r:op_file:s0,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/fota /vendor/fota ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,relatime,size=1428136k,nr_inodes=159879,mode=755,gid=1000 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
/dev/block/dm-2 /data ext4 rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,resuid=10010,data=ordered 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid 0 0
/data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid 0 0
/dev/block/vold/public:179,129 /mnt/media_rw/4847-9E8A vfat rw,nosuid,nodev,noexec,noatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/block/vold/public:179,129 /mnt/secure/asec vfat rw,nosuid,nodev,noexec,noatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/mnt/media_rw/4847-9E8A /mnt/runtime/default/4847-9E8A sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/4847-9E8A /storage/4847-9E8A sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/4847-9E8A /mnt/runtime/read/4847-9E8A sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/4847-9E8A /mnt/runtime/write/4847-9E8A sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
mcv5a:/data/local/tmp $
