### ISSUE TITLE
  [ SOLUTION HOW TO FIX ]        Oppo a5s root failed try again after new update CPH1909EX_11_A.42 / CPH1909EX11_a.41

### ISSUE THREAD

**Issue by 3ndlessly** [JunioJsv/mtk-easy-su#92]
Mtk.su member can't do anything about this so the only thing you must to do is downgrade you colorOS version back.

Item you need to downgrade without pc:
Memory card
Wifi
Time

Step1: click this link https://www.getdroidtips.com/cph1909ex_11_a-36-oppo-a5s-march-2020/#google_vignette

Step2: scroll down and try to find this [ CPH1909EX_11_a.39 ]
![Screenshot_2020-12-13-06-32-17-00](https://user-images.githubusercontent.com/75914535/101996427-3059e900-3d0d-11eb-8b06-8cc82ac32e22.jpg)

Step3: click   that link and download

( Extra to get save fail download at oppo website ) i can't give the link because I'm lazy

Step4: Open any app like ES FILE or something where can Move the download file to memory card. If you don't have click this link and download ES FILE PRO free https://an1.com/file_2570-dw.html

Step5: FUCK IM LAZY NOW!!!
[ open es file and move the file you  to sd card/ memory card ] if you don't know how open YouTube and learn!! Usu name tag "how to move the file to sd card es file pro"

Step6: shutdown u hp 

Step7: open "recovery mode" if u don't know how go and fucking open YouTube to learn with name tag "how to open recovery mode oppo"

Step8: select language English

Step9: click "install from storage device"

Bonus: is you hp have password. So fucking out the password!

Step10: select sd card 

Step11 : file you download [ CPH1909EX_11_a.39 ] and click to install

Step12: wait

Step13: wait

Step9999999: wait 

Step15: if FINISH! Reboot u hp back [ if you don't know how u fucking!

After all i want to said is you must downgrade you colorOS version to a.39😘

**Comment by JunioJsv** [comment]
Thanks

**Comment by DProBoy** [comment]
Quick question, so when I go into recovery mode, it doesn't detect my SD cards at all, I've tried to SD cards (samsung and kingston) and they just don't show up in install from storage. Would it be alright to install from phone storage ?

**Comment by 3ndlessly** [comment]
> Quick question, so when I go into recovery mode, it doesn't detect my SD cards at all, I've tried to SD cards (samsung and kingston) and they just don't show up in install from storage. Would it be alright to install from phone storage ?

That mean you must fix you sd card first like try to reset you phone service or something else if you don't know open YouTube/Google and learning.
But you can try to install from phone storage but 80% fail 😙 where i hope you lucky

**Comment by DProBoy** [comment]
Yep, indeed it fails ! It says the version I'm trying to install is lower than the current version .. Oh well !

**Comment by 3ndlessly** [comment]
> Yep, indeed it fails ! It says the version I'm trying to install is lower than the current version .. Oh well !

Sad boii.....try to fix you sd card with reset phone service or something like that...try to find in at YouTube

Btw....did you put you sd card in right way?

**Comment by DProBoy** [comment]
Yep, the SD card works like it's supposed to when I'm using the phone normally.. The problem is with recovery mode, it doesn't recognize my sd card there.

**Comment by 3ndlessly** [comment]
> Yep, the SD card works like it's supposed to when I'm using the phone normally.. The problem is with recovery mode, it doesn't recognize my sd card there.

Sooooo try to fix in!! YouTube and Google is demi god remember that .. use in

**Comment by 3ndlessly** [comment]
> Yep, the SD card works like it's supposed to when I'm using the phone normally.. The problem is with recovery mode, it doesn't recognize my sd card ther

> Thanks

Wc

**Comment by DProBoy** [comment]
I'm googling alright ! :"3 I just can't seem to find anything that pertains to ma problem. Thanks though !

**Comment by 3ndlessly** [comment]
> I'm googling alright ! :"3 I just can't seem to find anything that pertains to ma problem. Thanks though !

Btw im sorry I can't make the Torturial where...i dont have sd card + my phone suck i can't open my sim card place have something stuck in they.....i hope you lucky bro







Btw just wait to next colorOS version update

**Comment by DProBoy** [comment]
It's okay mate, I appreciate your effort in trying to help me ! 
PS : What's going to change with the next colorOS version update?

**Comment by 3ndlessly** [comment]
> It's okay mate, I appreciate your effort in trying to help me !
> PS : What's going to change with the next colorOS version update?

After i ask oppo help service they said they will fix in next update 😉 (next update in june)

**Comment by markjoseph22** [comment]
Does can reset everything like apps, game+obb, everything in phone storage if i downgrade my a5s latest to 39?

(sorry for my grammar)

**Comment by markjoseph22** [comment]
has anyone do it? Did you succeed?

**Comment by 3ndlessly** [comment]
No! Don't worry about it

**Comment by 3ndlessly** [comment]
Yes! But i hope u so if u hp doesn't suck

**Comment by 3ndlessly** [comment]
K

**Comment by Scrollax** [comment]
How bout with pc?

**Comment by kobi225** [comment]
when I downgrade will all files and apps be deleted?

**Comment by ezo-089** [comment]
Can I install it without sd card
(Note that I have 2.7 GB storage available now and the update file is 2.3 GB)

**Comment by zezo-089** [comment]
Hey @3ndlessly 
If I installed this downgraded version on oppo a5s
, Would it format my data?

**Comment by Waa42** [comment]
What will happen if ill downgrade my os through internal storage? Can I revert it back when something wrong happens?

**Comment by bishalachhami** [comment]
My versionA46 but not rotted how to solved??

**Comment by Craglitch** [comment]
This issue still open bruhhhhh

**Comment by Craglitch** [comment]
> Hey @3ndlessly If I installed this downgraded version on oppo a5s , Would it format my data?

No it wouldn't format your data

**Comment by zezo-089** [comment]
dude
it stills open
but whatever
i found how to root it anyway
(note: this thread was made by me !!)
 [https://forum.xda-developers.com/t/guide-root-unlock-bootloader-for-oppo-a5s-cph1909-after-security-update-without-downgrading-the-version-of-the-phone.4587745/](url)
